### ISSUE TITLE
Improve documentation for benchmarks

### ISSUE THREAD

**Issue by real-or-random** [bitcoin-core/secp256k1#1005]
A follow-up PR could add a `--help` which would also mention the `get_iters` environment variable (I have to look up in the source how it's called exactly every time).

_Originally posted by @jonasnick in https://github.com/bitcoin-core/secp256k1/pull/991#pullrequestreview-799481944_

We could also remove the indirection in `cirrus.sh` (https://github.com/bitcoin-core/secp256k1/blob/master/ci/cirrus.sh#L35-L37) and define the "right" constants directly in `cirrus.yml`. I tend to look the constants up in `cirrus.yml` and then see the wrong constants without the `SECP256K1_` prefix.

**Comment by jonasnick** [comment]
I was just suggesting to mention the string `SECP256K1_BENCH_ITERS` in case someone would want to use a custom number of iterations.
