### ISSUE TITLE
No way to extract a secret from a secp256k1_keypair: secp256k1_keypair_priv()?

### ISSUE THREAD

**Issue by rustyrussell** [bitcoin-core/secp256k1#1014]
In the x-only world, it makes sense to carry around `secp256k1_keypair` instead of raw secrets.

However, this means there's no way of accessing secret, i.e. `secp256k1_keypair_priv()`.

I actually want this for debugging, but logically I'd want it if I were to send secrets over the wire...

**Comment by real-or-random** [comment]
https://github.com/bitcoin-core/secp256k1/blob/master/include/secp256k1_extrakeys.h#L173-L184

;)

**Comment by jonasnick** [comment]
can we close this? @rustyrussell

**Comment by real-or-random** [comment]
Closing for now, we can still reopen in case there are further questions.
