### ISSUE TITLE
tweaking seckey vs. tweaking keypair and their impact on seckey

### ISSUE THREAD

**Issue by scgbckbone** [bitcoin-core/secp256k1#1021]
```python3
keypair = keypair_create(seckey)
tweaked_keypair = keypair_xonly_tweak_add(keypair, tweak)
tweaked_seckey = ec_seckey_tweak_add(seckey, tweak)
# seckeys tweaked by different methods do NOT equal
tweaked_seckey != keypair_sec(tweaked_keypair)  # --> True (they do NOT equal)
# seckey from keypair is however changed after tweaking
seckey != keypair_sec(tweaked_keypair)  # --> True (do NOT equal)
```
Why tweaking keypair does NOT tweak seckey same as tweaking seckey via `ec_seckey_tweak_add` ? Also what does it do with seckey 
as it is changed (last line of pseudo code).

documentation comment for `secp256k1_keypair_xonly_tweak_add`:
_Tweak a keypair by adding tweak32 to the secret key and updating the public key accordingly._

**Comment by sipa** [comment]
The difference isn't due to a difference between seckeys and keypairs as such, but due to the fact that the seckey tweaking functions are x-only compatible, and the individual sec/pubkey tweak functions are not. When tweaking x-only keys, the implicit negations are handled when odd Y coordinates are reached.

**Comment by scgbckbone** [comment]
got it - thanks

**Comment by scgbckbone** [comment]
This how to get correct tweaked seckey from both methods:
```python
keypair = keypair_create(seckey)
xonly_pub, pk_parity = keypair_xonly_pub(keypair)
tweaked_keypair = keypair_xonly_tweak_add(keypair, tweak)
if pk_parity == 0:
    tweaked_seckey = ec_seckey_tweak_add(seckey, valid_tweak)
else:
    tweaked_seckey = ec_seckey_tweak_add(ec_seckey_negate(seckey), valid_tweak)
tweaked_seckey == keypair_sec(tweaked_keypair)  # --> True (they DO equal)
```
