### ISSUE TITLE
build: Rename arm to arm32 and check if it's really supported

### ISSUE THREAD

**Issue by real-or-random** [bitcoin-core/secp256k1#1034]
See the discussion starting here: https://github.com/bitcoin-core/secp256k1/pull/936#issuecomment-831473420

**Comment by real-or-random** [comment]
Have a look at configure.ac. You need to be familiar with shell scripting, and you need to figure out a way to detect arm32 support. The autoconf documentation may be useful. (https://www.gnu.org/software/autoconf/)

**Comment by real-or-random** [comment]
@Psycho-Pirate Are you still interested in working on this?

**Comment by hebasto** [comment]
At least in CMake-based build system, it seems worth making the `SECP256K1_ASM` option actually dependent on the value of the `CMAKE_SYSTEM_PROCESSOR` variable. Then `ON`/`OFF` values will be enough for it with defaults as follows:
- `ON` for `x86_64`
- `OFF` for `arm`
