### ISSUE TITLE
Stronger magnitude check for normalized field element in `_fe_verify`

### ISSUE THREAD

**Issue by siv2r** [bitcoin-core/secp256k1#1059]
https://github.com/bitcoin-core/secp256k1/blob/a1102b12196ea27f44d6201de4d25926a2ae9640/src/field.h#L16-L18

According to the comment above, wouldn't it be better to have the check `r &= (a->magnitude = 1 || a->magnitude = 0);`? Instead of the ones below.

https://github.com/bitcoin-core/secp256k1/blob/a1102b12196ea27f44d6201de4d25926a2ae9640/src/field_5x52_impl.h#L51-L52

https://github.com/bitcoin-core/secp256k1/blob/a1102b12196ea27f44d6201de4d25926a2ae9640/src/field_10x26_impl.h#L39-L40

**Comment by siv2r** [comment]
My bad, I forgot that a->magnitude was `int`.

**Comment by real-or-random** [comment]
Well, I think *because* it is `int`, it would make sense to exclude negative values. But we already to this here (not conditioned on `normalized`): https://github.com/bitcoin-core/secp256k1/blob/a1102b12196ea27f44d6201de4d25926a2ae9640/src/field_10x26_impl.h#L37
