### ISSUE TITLE
Support more Schnorr schemes besides BIP340

### ISSUE THREAD

**Issue by Sajjon** [bitcoin-core/secp256k1#1070]
There are two different Schnorr signature variants in _bitcoin-core/secp256k1_, the "default" one named `secp256k1_schnorrsig_sign` and another more customizable with the appropriate name `secp256k1_schnorrsig_sign_custom`. Both functions calls `secp256k1_schnorrsig_sign_internal`.  Using `secp256k1_schnorrsig_sign_custom` we can pass custom nonce data through the `secp256k1_schnorrsig_extraparams` parameter, which has a member for a custom nonce function, `secp256k1_nonce_function_hardened noncefp`. This looks great at first glance! Looks like I can use _bitcoin-core/secp256k1_ as a provider of a great Schnorr sig implementation! However, the `secp256k1_schnorrsig_sign_custom` is not as customizable as it could be, or as I want to be, because `secp256k1_schnorrsig_sign_internal` **hardcodes** the `algo` to `bip340_algo` (with value `"BIP0340/nonce"`), when calling the nonce function:

```c
    ret &= !!noncefp(buf, msg, msglen, seckey, pk_buf, bip340_algo, sizeof(bip340_algo), ndata);
```

I propose we change this hardcoded value, to allow consumers of this amazing lib, to pass along a custom `algo` string. 

I've recently started writing a Swift wrapper called [K1](https://github.com/Sajjon/K1). The earliest (AFAIK) adopter of Schnorr signatures amongst cryptocurrency community is [Zilliqa](https://www.zilliqa.com/), which has been using Schnorr since 2017/2018. The [Zilliqa-JS javascript library](https://github.com/Zilliqa/zilliqa-js/tree/dev/packages/zilliqa-js-crypto) has in [earlier commits bundled 1000 test vectors](https://github.com/Zilliqa/zilliqa-js/blob/a15df2ed9db135170a098c70df35ba2aa09dd0fd/packages/zilliqa-js-crypto/test/schnorr.fixtures.json) which I thought to be useful. 

I would also like to make it possible for my library _K1_ to replace my own, unsafe, EC library called [_EllipticCurveKit_](https://github.com/Sajjon/EllipticCurveKit), which currently is used  (potentially unsafe for end users, which they are informed about) by the [iOS Zilliqa wallet _Zhip_ (open source)](https://github.com/OpenZesame/Zhip) (also [on AppStore](https://apps.apple.com/us/app/zhip/id1455248315)). 

The bad news is that Zilliqa [uses the ALGO name `"Schnorr+SHA256  "`](https://github.com/Zilliqa/zilliqa-js/blob/dev/packages/zilliqa-js-crypto/src/schnorr.ts#L37). So I cannot replace _EllipticCurveKit_ in _Zhip_ with _K1_ until I'm able to pass a custom  (`"Schnorr+SHA256  "`) ALGO to `secp256k1_schnorrsig_sign_custom`.

Furthermore, Zilliqa uses [this HMAC-DRBG as nonce function](https://github.com/Zilliqa/zilliqa-js/blob/dev/packages/zilliqa-js-crypto/src/schnorr.ts#L231-L251), but I should be able to implement that in `C` and pass through the `noncefp` member in `secp256k1_schnorrsig_extraparams`, right?

Thanks!

**Comment by Sajjon** [comment]
If PRs are welcome, I might give it a go? That is, if you all think it a good idea to support this?

**Comment by sipa** [comment]
You can provide a custom nonce function to accomplish this. It could ignore the algo passed, and use whatever prefix it wants.

**Comment by sipa** [comment]
Oh this isn't about the nonce function anymore, but the challenge hash.

Yes, that's hardcoded. The schnorrsig module implements the signature scheme defined in BIP340, not other schemes.

**Comment by Sajjon** [comment]
@sipa yeah sorry if I was unclear.

Ok got it. Hmmm. Is that something we might wanna reconsider? 

This amazing library would add great value to the whole crypto-community if it could support more Schnorr schemes besides BIP340, and I think support for custom Challenge function pointer might be enough for many. At least for Zilliqa.

**Comment by real-or-random** [comment]
> So: I'm asking if it would be possible to add yet another function pointer to `secp256k1_schnorrsig_extraparams`, being a pointer for a customizable `secp256k1_schnorrsig_challenge` and instead of having:

This has a huge footgun potential because you leak the secret key if you sign twice with the same nonce but different challenge hashes.

Besides, I don't think it would solve your problem. AFAICT from a glimpse at the code you linked, their scheme does not use x-only public keys, and the signatures are different: The first component is a hash and not a point as in BIP340. "Schnorr signatures" are an abstract concept. If you want a concrete scheme, you need to make a few design decisions and those in BIP340 are different than what you're looking for. 

This library is made for the Bitcoin universe. If you want something else, you need to fork it.

**Comment by Sajjon** [comment]
@real-or-random thanks! Yeah I figured there are risks if not done right.

Hopefully we will see many other projects adopting BIP340 instead of using there own Challenge fn etc. 

Thanks!
