### ISSUE TITLE
Public key is always two characters too long

### ISSUE THREAD

**Issue by Postsalut** [bitcoin-core/secp256k1#1081]
When using the code from the example (ecdsa.c), the output, consistently, shows a public key that is 66 characters long when compressed and 130 when uncompressed (that is excluding the prepended "0x"). Isn't it supposed to be 64 and 128 characters long respectively, or am I missing something?

**Comment by real-or-random** [comment]
That's correct, see https://github.com/bitcoin-core/secp256k1/blob/master/include/secp256k1.h#L368 .
