### ISSUE TITLE
VIsual Studio-19, C++, Windows

### ISSUE THREAD

**Issue by DaRallis** [bitcoin-core/secp256k1#1092]
Hey, could anyone guide me how could I use this library on Win OS in a c++ app? I'm little confused.

**Comment by real-or-random** [comment]
Maybe this comment helps: https://github.com/bitcoin-core/secp256k1/issues/917#issuecomment-817841750

**Comment by MrMonotone** [comment]
After a bit of playing around I was able to build a lib for my use. Perhaps this will help others...
`cl /c /MT -I. -DUSE_NUM_NONE=1 -DUSE_ECMULT_STATIC_PRECOMPUTATION=1 -DECMULT_GEN_PREC_BITS=4 -DUSE_FIELD_INV_BUILTIN=1 -DUSE_SCALAR_INV_BUILTIN=1 -DUSE_FIELD_10X26=1 -DUSE_SCALAR_8X32=1 -DECMULT_WINDOW_SIZE=15 -DENABLE_MODULE_SCHNORRSIG=1 -DENABLE_MODULE_ECDH=1 -DENABLE_MODULE_EXTRAKEYS=1 src/secp256k1.c src/precomputed_ecmult.c src/precomputed_ecmult_gen.c
lib secp256k1.obj precomputed_ecmult_gen.obj precomputed_ecmult.obj`

**Comment by real-or-random** [comment]
@MrMonotone Note that a lot of `-D` options you give here are old (and ignored). Unfortunately we currently don't have a nice list of options. (That's on our todo list...) For the moment, https://github.com/bitcoin/bitcoin/blob/master/build_msvc/libsecp256k1/libsecp256k1.vcxproj#L17 is probably a good resource.
