### ISSUE TITLE
What will be the security risks if we persist "e" as part of schnorr signature=(r,s,e) and get publicKey from signature at verification

### ISSUE THREAD

**Issue by sarvalabs-sai** [bitcoin-core/secp256k1#1096]
Hi folks, 

We know Unlike `ecrecover`, it is impossible to get to public key given schnorr signature = (r,s) since `rG = sG-eP` . 

So, would like to understand what are the security risks

if we say 
`signature=F(r,s,e)` 
and get to publicKey at the verification? something like this
`P = (rG-sG)/e`

**Comment by real-or-random** [comment]
Closing because this is not an issue with the library. The same question was asked here. https://bitcoin.stackexchange.com/questions/113060/what-will-be-the-security-risks-if-we-persist-e-as-part-of-schnorr-signature

**Comment by sarvalabs-sai** [comment]
Hey @real-or-random 

Appreciate, if you can help me by answering that question there atleast
