### ISSUE TITLE
`make` creates non-executable example files

### ISSUE THREAD

**Issue by w0xlt** [bitcoin-core/secp256k1#1098]
I'm trying to compile the example files, performing the steps below, as described in `README.md`:

    $ ./autogen.sh
    $ ./configure --enable-module-schnorrsig --enable-module-ecdh --enable-examples
    $ make 
    $ make check 

But the files generated are not executable.
    
    ....
    -rw-rw-r--  1 user01 user01  5432 Apr  2 18:24 ecdh.c
    -rw-rw-r--  1 user01 user01 26376 Apr  2 19:32 ecdh_example-ecdh.o
    -rw-rw-r--  1 user01 user01  6026 Apr  2 18:24 ecdsa.c
    -rw-rw-r--  1 user01 user01 16896 Apr  2 19:32 ecdsa_example-ecdsa.o
    ....
  
I tried changing `chmod +x ecdh_example-ecdh.o`, for example, but got the error:

```
Failed to execute process './ecdh_example-ecdh.o'. Reason:
exec: unknown error (errno was 8)
The file './ecdh_example-ecdh.o' is marked as an executable but could not be run by the operating system.
```

OS: Ubuntu 21.10, gcc 11.2.0, clang 13.0.0-2

**Comment by sipa** [comment]
You're looking at the object files, not the executables. The executables are in the root directory (not in `examples/`); look for `ecdh_example`, `ecdsa_example`, `schnorr_example`.

**Comment by w0xlt** [comment]
Yes, they are in the root directory. My mistake. Thanks for quick reply.
