### ISSUE TITLE
Can scalar_4x64 implementations be auto vectorized by compiler?

### ISSUE THREAD

**Issue by t-anyu** [bitcoin-core/secp256k1#1110]
Hey,

I played around with different compiler settings, but didn't notice any proper speed gains in pubkey generation, signing and verification. I'm wondering if these scalar functions are optimized to use SIMD instructions by default (-march=native, -O2/O3)? Or would should the code be replaced with intrisinc functions in order to use e.g. AVX.

Thanks

**Comment by real-or-random** [comment]
> I'm wondering if these scalar functions are optimized to use SIMD instructions by default 

Currently, they are not. One of our primary goals is to have an implementation that performs well on almost all architectures, and our code is in fact pretty good even without SIMD. We'd be interested in SIMD optimizations for common platforms such as x86_64 but I'm not aware that anyone is actively working on this right now.

**Comment by real-or-random** [comment]
Closing because the question has been answered. Feel free to discuss further.
