### ISSUE TITLE
release: Checking binary compatibility

### ISSUE THREAD

**Issue by real-or-random** [bitcoin-core/secp256k1#1136]
When looking into binary compatibility (see #1055, #964), I found this nice website which describes best practices and open source tools for checking binary compatibility: https://abi-laboratory.pro This may be something to look into *after* the first release (but maybe before the second release).

See for example [the report for Botan](https://abi-laboratory.pro/index.php?view=timeline&l=botan), [which by the way doesn't provide binary compatibility across versions at all](https://botan.randombit.net/handbook/abi.html).

**Comment by hebasto** [comment]
FWIW, here is what I've got for the recent releases:
- [API compatibility report for the libsecp256k1.so object between 0.2.0 and 0.3.0 versions on x86_64](https://htmlpreview.github.io/?https://github.com/hebasto/artefacts/blob/master/libsecp256k1%20ABI%20compatibility/compat_reports/libsecp256k1/0.2.0_to_0.3.0/compat_report.html)
- [API compatibility report for the libsecp256k1.so object between 0.3.0 and 0.3.1 versions on x86_64](https://htmlpreview.github.io/?https://github.com/hebasto/artefacts/blob/master/libsecp256k1%20ABI%20compatibility/compat_reports/libsecp256k1/0.3.0_to_0.3.1/compat_report.html)

**Comment by hebasto** [comment]
> @hebasto I don't understand how that commit can have any effect on the public ABI.

Neither do I. That was reported by the tool. Maybe a false positive report?

**Comment by hebasto** [comment]
No issues with gcc-10:
- [0.2.0 --> 0.3.0](https://htmlpreview.github.io/?https://github.com/hebasto/artefacts/blob/gcc-10/libsecp256k1%20ABI%20compatibility/compat_reports/libsecp256k1/0.2.0_to_0.3.0/compat_report.html)
- [0.3.0 --> 0.3.1](https://htmlpreview.github.io/?https://github.com/hebasto/artefacts/blob/gcc-10/libsecp256k1%20ABI%20compatibility/compat_reports/libsecp256k1/0.3.0_to_0.3.1/compat_report.html)

**Comment by real-or-random** [comment]
Interestingly, the dumps generated with gcc 10 don't have any "Reg"(ister) entries in their json file, whereas the dumps generated with gcc 11 list registers for some arguments...  

Maybe open an issue with the tool?
