### ISSUE TITLE
Constant-time tests on macOS

### ISSUE THREAD

**Issue by sipa** [bitcoin-core/secp256k1#1151]
I noticed this in the CI output:

[We are sunsetting support for Intel-based macOS instances! Please migrate before January 1st 2023.](https://cirrus-ci.org/guide/macOS/)

**Comment by MarcoFalke** [comment]
Is this fixed now?

**Comment by real-or-random** [comment]
from #1152:

> It drops valgrind and the ctime tests on macOS, as valgrind simply isn't supported anymore there. We may recover some of that functionality by adding MSan (https://github.com/bitcoin-core/secp256k1/pull/1155) for memory-checking there, and adding ctime-using-mtime (TODO).

I think we should leave it open until this has been fixed.

**Comment by real-or-random** [comment]
Oh, the valgrind fork now works on Ventura https://github.com/LouisBrunner/valgrind-macos/issues/54#issuecomment-1377334552 (except for memory leak tracking, which is still WIP but that shouldn't be required for our purposes.) So we should probably https://github.com/bitcoin-core/secp256k1/pull/1152/commits/c0ae48c9950a908b637bff27791fabbe2833c4a5 partly.

**Comment by hebasto** [comment]
>    * [ ]  Enable MSan for MacOS

https://clang.llvm.org/docs/MemorySanitizer.html#supported-platforms:
> MemorySanitizer is supported on the following OS:
>    * Linux
>    * NetBSD
>    * FreeBSD

**Comment by real-or-random** [comment]
Oh indeed, MSan doesn't work on Clang...

>   * [x]  Make the constant-time tests work on MSan

And this has been solved by https://github.com/bitcoin-core/secp256k1/pull/1169.

This means that there's nothing to do for us here except to wait for https://github.com/LouisBrunner/valgrind-macos/issues/56. This will make it possible to run Valgrind on macOS again. 

Leaving this open to track this.
