### ISSUE TITLE
Setting counting_illegal_callback may hide failing tests

### ISSUE THREAD

**Issue by jonasnick** [bitcoin-core/secp256k1#1167]
The following code snippet very roughly resembles what happens in the libsecp test harness and illustrates the issue:

```C
/* in the tests we have access to a global context */
static secp256k1_context *ctx = NULL;

void test_foo() {
  int ecount;
  context_set_error_callback(ctx, counting_illegal_callback_fn, &ecount);
  /* do some tests with ecount */
}
void test_bar() {
  /* we don't set the counting_illegal_callback here because we don't want to test that here */
  some_function(ctx);
}
void main() {
  test_foo();
  test_bar();
}
```

The code is fine, until one day `some_function(ctx)` results in the illegal callback being called.
Then we'd want the test to fail but instead what happens is that some stack region formerly known as `ecount` is modified, which does not necessarily result in a crash.

One solution would be to never add the `counting_illegal_callback` to the global context and instead create a local context for counting.

**Comment by real-or-random** [comment]
> One solution would be to never add the `counting_illegal_callback` to the global context and instead create a local context for counting.

Or make the ecount global. :shrug: I guess that's good enough for test code.

**Comment by apoelstra** [comment]
We could write an `EXPECT_ARG_CHECK_FAIL` macro (or maybe something with a nicer name :)) which creates a fresh `ecount` variable at 0, sets the context object's error callbacks, checks the `ecount` is 1, then restores the old callbacks.

This would also get rid of all the ecount-accounting code, which is quite a PITA to maintain and sometimes results in huge diffs.

**Comment by real-or-random** [comment]
We have `CHECK_ILLEGAL` and `CHECK_ILLEGAL_VOID` since e39d954f118a29db2c33e9a9a507053fff5573ed:

https://github.com/bitcoin-core/secp256k1/blob/c545fdc374964424683d9dac31a828adedabe860/src/tests.c#L55-L72

The "only" thing left to do is to use these everywhere (and maybe introduce a similar macro for the error callback).
