### ISSUE TITLE
release: Refine process

### ISSUE THREAD

**Issue by real-or-random** [bitcoin-core/secp256k1#1176]
Some questions that popped up during the 0.2.0 release:

 * Maintenance release: In fact we could have multiple PRs here before the release PR. Do we want to write this down?
 * Should we add instructions to check the contents of `make dist` / run `make distcheck`?
 * Add instructions to run symbol check (after #1135)?

**Comment by hebasto** [comment]
>  * Add instructions to run symbol check (after #1135)?

:+1:

**Comment by real-or-random** [comment]
Release schedule (from [IRC meeting 2023-01-16](https://gnusha.org/secp256k1/2023-01-16.log)):
 - Twice as often as a major release of Core (which is every 6-7 months), i.e., every 3-4 months for us. We try to aim to one month before feature freeze of [Core major release](https://github.com/bitcoin/bitcoin/issues/26549) for every second of our releases. Of course, we can still create more releases whenever we feel there's need, e.g., for bugfixes.
 - That means the next planned release will be on/around 2023-03-01.

**Comment by real-or-random** [comment]
Another thing that's good to sanity-check before release (even if done manually) is if the result of `make install` looks reasonable (e.g., set of files is correct). This can be done best with by installing to some temporary location, i.e., `--prefix=/tmp/install` or `-DCMAKE_INSTALL_PREFIX=/tmp/install`.
