### ISSUE TITLE
Error from commit  2bca0a5cbf756dd4ff1f0bda4585a7d3c64e1480

### ISSUE THREAD

**Issue by kcw-grunt** [bitcoin-core/secp256k1#1253]
#Problem
`secp256k1_scratch_space_destroy line 134`

There seem to be conflicting types here causing an issue in using the lib

**Comment by jonasnick** [comment]
Please describe exactly what steps you're performing and what the exact error message is.

**Comment by kcw-grunt** [comment]
We see in an integration of the library to our Android codebase.  And it may be due to dependency update (this lib is used 2x in our implementation)

I may close this issue.  Could you standby for 1 day? @jonasnick 

#### Error:
`error: conflicting types for 'secp256k1_scratch_space_destroy'`

**Comment by kcw-grunt** [comment]
@jonasnick 
We are simply reverting to 0.2.0 because the config worked in our implementation 

closing
