### ISSUE TITLE
ci: Test with unreleased / experimental / nightly compilers

### ISSUE THREAD

**Issue by real-or-random** [bitcoin-core/secp256k1#1271]
If we do this, we can catch issues like the recent constant-time problem early enough. I already had some local notes on this. Here's a list of helpful resources for Debian:

* https://wiki.debian.org/DebianExperimental
  * https://packages.debian.org/experimental/clang-17
  * https://packages.debian.org/de/experimental/gcc-13
* https://jwakely.github.io/pkg-gcc-latest/
* https://apt.llvm.org/

**Comment by fanquake** [comment]
One thing to keep in mind here, is the increased likelyhood of spurious CI failures when running on experimental distros. Pcakages can be changing daily, and can be mis-packaged, or broken in various ways, causing build failures or other issues. The same `apt install x y z` invocation won't necessarily work one day to the next etc. We've seen this somewhat with debian:experimental.

**Comment by real-or-random** [comment]
Thanks, I'm fully aware that we may see random failures. My thinking is that it's still worth it in the end. It's probably a good idea to run these tests as nightly tests and not for PRs, so that random failures don't get in the way of normal dev work. 

> We've seen this somewhat with debian:experimental.

Has this been used in Core? I wasn't aware, and I'm happy to hear more about your experiences. 

I could imagine that apt.llvm.org is the better choice for clang, so we'd need debian:experimental only for gcc.

**Comment by fanquake** [comment]
> Has this been used in Core?

Not in the main repo. However other in repos / infra, it has been, i.e https://github.com/MarcoFalke/b-c-nightly. If you look through the commits in that repo, there are plenty of examples of random failures, i.e this merge: https://github.com/MarcoFalke/b-c-nightly/commit/458334fc1c141a6fc68f61f4bfe5a051c39d5699, all of the `debian:experimental` jobs failed because [apt couldn't figure out how to install `git-man`](https://github.com/MarcoFalke/b-c-nightly/runs/12040138387):
```bash
The following packages have unmet dependencies:
 git : Depends: git-man (< 1:2.39.2-.) but 1:2.39.2+next.20230215-1 is to be installed
       Recommends: less but it is not going to be installed
       Recommends: ssh-client
E: Unable to correct problems, you have held broken packages.
```

**Comment by real-or-random** [comment]
Thanks, good to know. Our builds should be much simpler, but we could think about sharing some pieces for keeping Debian experimental work on Cirrus. I guess all we want is an experimental GCC in the end, but I can see that can also lead to failures.
