### ISSUE TITLE
ci: bring bitcoin's .py linter into secp256k1

### ISSUE THREAD

**Issue by RandomLattice** [bitcoin-core/secp256k1#1278]
Now that https://github.com/bitcoin-core/secp256k1/pull/1245 introduced a build-time dependency on python3, we probably want to run bitcoin's python linter in this repo. @sipa had to disable this in https://github.com/bitcoin/bitcoin/pull/27445 since we didn't catch linting errors in secp256k1's CI but only in bitcoin's CI.

What would be a good course of action? Some options:
1. Add a CI job in secp256k1 to do a shallow clone of bitcoin master and run the linter
2. Copy linter scripts from bitcoin into secp256k1

No option is perfect: 1. is probably a bit heavy, and 2 will get outdated. I am leaning towards 1. Thoughts?

**Comment by real-or-random** [comment]
To be honest, I lean towards doing nothing.

For example, I don't see that https://github.com/bitcoin-core/secp256k1/pull/1279 is an obvious improvement in readability. We also don't (syntax) linting for our C files, and I think our experience with that is rather good. It provides authors with a bit more freedom in making deliberate choices about their code. Of course, that freedom comes with responsibility, but we're a small project, and we never had real issues with that. Things may be different in Core with many different contributors.  

Moreover, we have more *.py files, they just masquerade as *.sage files. So if we start linting .py, we'd also need to lint *.sage, and that probably requires more effort without clear benefits. 

And I don't think disabling linting in https://github.com/bitcoin/bitcoin/pull/27445 should be a temporary solution. It's just wrong for Core to lint vendored code.

**Comment by ekzyis** [comment]
This can be closed, right?
