### ISSUE TITLE
Missing method to add 2 points

### ISSUE THREAD

**Issue by genjix** [bitcoin-core/secp256k1#13]
What is the recommended way to add 2 points?

I see:

Create point: void static secp256k1_gej_set_xy(secp256k1_gej_t *r, const secp256k1_fe_t *x, const secp256k1_fe_t *y);

Add both points: void static secp256k1_gej_add(secp256k1_gej_t *r, const secp256k1_gej_t *a, const secp256k1_gej_t *b);

And then finally convert the jacobian point back into a cartesian value (0x04, x, y) as used in Bitcoin.

(using x/z^2 and y/z^3 as it says in group.h)

**Comment by apoelstra** [comment]
Closing. It's been a few years and (a) we haven't encountered a use case for this; (b) we've formed a policy of not exposing arbitrary EC math functionality, at risk of people using them to create novel cryptosystems in inefficient/insecure ways.

If you need to add points, the right way to do it is to encapsulate whatever you're really doing into a module, fork the lib to add it under `src/modules`,  and give a safe public API. If it's generally useful, PRs are welcome.

**Comment by voisine** [comment]
@apoelstra in breadwallet we are using point addition and multiplication, and scalar addition directly to implement BIP32 and BIP38. What's the recommended best practice to do this using libsecp? Should we make a libsecp module for it?

**Comment by sipa** [comment]
I believe the secp256k1_ec_{priv,pub}key_tweak_* functions sufice for BIP32
and BIP38.

**Comment by voisine** [comment]
done https://github.com/voisine/breadwallet/blob/555d0b2528894805c5a9b46c2c6efebc11205b9f/BreadWallet/BRKey.m#L46-L102
