### ISSUE TITLE
ci: Add a constant-time test job that uses MSan

### ISSUE THREAD

**Issue by real-or-random** [bitcoin-core/secp256k1#1388]
All our constant-time tests on CI use Valgrind (which has more precise tracking of undefined memory than MSan). However, we should also have a MSan job on CI, if only to check that the constant-time tests work on MSan.

**Comment by hebasto** [comment]
Isn't it done in 5e2e6fcfc0ebcdaad96fda9db9b8946d8bcdc8e5?

**Comment by real-or-random** [comment]
Oh sure, I forgot about that one...
