### ISSUE TITLE
ci: Random Valgrind MacOS build failures

### ISSUE THREAD

**Issue by real-or-random** [bitcoin-core/secp256k1#1439]
I had to restart this job because make failed for Valgrind MacOS:
https://github.com/bitcoin-core/secp256k1/actions/runs/6777069897/job/18419944841?pr=1437

We've seen other (different) random build issues before: https://github.com/LouisBrunner/valgrind-macos/issues/26

We could print the logs The make log is in `/Users/runner/Library/Logs/Homebrew/valgrind/04.make`. Perhaps cat just all of ``/Users/runner/Library/Logs/Homebrew/valgrind/*`

But I suspect these are concurrency issues. We could prefix the command with `MAKEFLAGS="-j1"` when we call brew. Or just retry make if it fails... cc @hebasto

**Comment by real-or-random** [comment]
Hm, this is another one, but this one is a linker error and it looks very similar to https://github.com/LouisBrunner/valgrind-macos/issues/26: 
https://github.com/bitcoin-core/secp256k1/actions/runs/6756875722/job/18366814430?pr=1184#step:4:245

I don't know to be honest...

**Comment by hebasto** [comment]
Is this still an issue?

**Comment by real-or-random** [comment]
Hm, not entirely sure, but I haven't seen this in a while. Let's just close the issue, it's anyway not very actionable. And we can always reopen.
