### ISSUE TITLE
secp256k1_fe_set_b32_mod doesn't actually reduce anything

### ISSUE THREAD

**Issue by Coding-Enthusiast** [bitcoin-core/secp256k1#1453]
`secp256k1_fe_set_b32_mod` method name and comment suggest that it reduces the value mod p and the result is supposed to be `r ≡ a (mod p)`  
https://github.com/bitcoin-core/secp256k1/blob/d3e29db8bbf81600fe0a6bd70b12fe57a0121b83/src/field.h#L187-L192  

However looking at the implementations they don't actually perform any reduction. It's just a simple conversion from byte[] to uint[] in radix 26 or 52.  
https://github.com/bitcoin-core/secp256k1/blob/d3e29db8bbf81600fe0a6bd70b12fe57a0121b83/src/field_impl.h#L270-L277  
https://github.com/bitcoin-core/secp256k1/blob/d3e29db8bbf81600fe0a6bd70b12fe57a0121b83/src/field_10x26_impl.h#L293-L304   
https://github.com/bitcoin-core/secp256k1/blob/d3e29db8bbf81600fe0a6bd70b12fe57a0121b83/src/field_5x52_impl.h#L235-L270  

After this change the old method (`secp256k1_fe_set_b32_limit`) is still used in most places except something like this 
https://github.com/bitcoin-core/secp256k1/commit/5b32602295ff7ad9e1973f96b8ee8344b82f4af0#diff-6f71b0372be086d45b4f2740508c03a21835d87008840032fbb767f419fd988a  
And it just assumes `secp256k1_fe_set_b32_mod` reduces the result while it doesn't.  

@sipa

**Comment by Coding-Enthusiast** [comment]
> So the only difference between `secp256k1_fe_set_b32_mod` and `secp256k1_fe_set_b32_limit` is that the latter detects and fails if the input exceeds p

Wouldn't it be better to rename the methods to something like `_set_b32` and `set_b32_check`?

**Comment by real-or-random** [comment]
Well, bike shedding is always possible, but I think the names are okay. If anything, `limit` is more precise than `check`, and `mod` is more precise than the empty string. 

Perhaps the docs can be marginally improved. I see that this can be misleading.
> Set a field element equal to a provided 32-byte big endian value, reducing it.

It's more like this:
"Set a field element equal to the element represented by a provided 32-byte big endian value interpreted modulo p."


And the other one:
> Set a field element equal to a provided 32-byte big endian value, checking for overflow.

Perhaps:
"Set a field element equal to a provided 32-byte big endian value in [0..p]."

**Comment by real-or-random** [comment]
@Coding-Enthusiast I'd be happy to review a PR which implements (variants of) these suggestions.
