### ISSUE TITLE
No implementation found

### ISSUE THREAD

**Issue by d1mpi** [bitcoin-core/secp256k1#1464]
Hello

No implementation found for long org.bitcoin.Secp256k1Context.secp256k1_init_context() (tried Java_org_bitcoin_Secp256k1Context_secp256k1_1init_1context and Java_org_bitcoin_Secp256k1Context_secp256k1_1init_1context__) - is the library loaded, e.g. System.loadLibrary?

I built a library for Android using the command

-S . -B ./build \ 
-DCMAKE_TOOLCHAIN_FILE=${ANDROID_NDK_ROOT}/build/cmake/android.toolchain.cmake \
-DANDROID_ABI=x86_64 \
-DANDROID_NATIVE_API_LEVEL=33

cmake --build ./build -j 4

The file libsecp256k1.so I put it in the jniLibs/x86_64 folder
I used Secp256k1Context.IsEnabled() from bitcoinj in the project, it starts System.LoadLibrary under the hood

Android SDK 34
Java Version 17
ADV Pixel 7 Pro

Nothing helps

**Comment by real-or-random** [comment]
>  I used Secp256k1Context.IsEnabled() from bitcoinj in the project, it starts System.LoadLibrary under the hood

Hi, this is the repository for the C library libsecp256k1. We don't provide support for bitcoinj problems. Please reach out to bitcoinj for help. If the bitcoinj maintainers think this is an issue on our side, we will look into it.

**Comment by real-or-random** [comment]
Closing this for now, we can always reopen if this is an issue on our side.
