### ISSUE TITLE
fe_sqr tests could be improved

### ISSUE THREAD

**Issue by Coding-Enthusiast** [bitcoin-core/secp256k1#1472]
https://github.com/bitcoin-core/secp256k1/blob/efe85c70a2e357e3605a8901a9662295bae1001f/src/tests.c#L3289-L3303  

This method doesn't test anything and after looking through commits it was added in https://github.com/bitcoin-core/secp256k1/commit/59447da38d6fa394ab7b10f32aea55930da732be and got removed in the next commit https://github.com/bitcoin-core/secp256k1/commit/21f81a846957408d4a2fe30cff32370567887a93. I'm not sure what the "problem" mentioned in the first commit is but if it is checking it using the `SECP256K1_FE_VERIFY` method, it is pointless to call `run_sqr` without this build configuration.

**Comment by real-or-random** [comment]
> it is pointless to call `run_sqr` without this build configuration.

Well, there's nothing wrong with it, except that it adds a few milliseconds to the noverify_tests. I claim that adding `#ifdefs` isn't worth the complexity and the development time. So this is not an issue.

The test itself could perhaps be improved. We could compare with the result of another method, e.g., `fe_mul`. We can't use `fe_mul` to compute `x*x` directly (see docs) but we could, e.g., check that `(x+y)*(x-y) = x^2 - y^2` for some random values `y != 0`.

**Comment by real-or-random** [comment]
@Coding-Enthusiast 

> we could, e.g., check that `(x+y)*(x-y) = x^2 - y^2` for some random values `y != 0`.

Do you want to give it a try and work on a PR?

**Comment by Coding-Enthusiast** [comment]
Sadly my C skills are readonly 😊

**Comment by real-or-random** [comment]
We all started small... ;)

**Comment by real-or-random** [comment]
This has been resolved by #1490.
