### ISSUE TITLE
tests: Tidy the util functions

### ISSUE THREAD

**Issue by real-or-random** [bitcoin-core/secp256k1#1491]
When I look at all the helper functions near the top of `tests.c`, there are still some things that could be improved:
 - A lot of these functions could be moved to `testutil` or `testrand`, also functions like `random_fe`, `random_fe_magnitude`. They're currently only in `tests.c` but they're utils in the end.
 - We have functions with `group_element` and `field_element`, but they should just be `ge` and `fe`.
 - The ones in `testutil` should probably also get a `secp256k1_testutil` prefix then. You could say it's good that they stand out currently, but at least that's inconsistent with the ones in `testrand`, which have a prefix. Or perhaps better: we use prefixes `testutil_` and `testrand_`, dropping the additional `secp256k1_` for test functions. Then they still stand out. (The main purpose of `secp256k1_` is to avoid namespace collisions if someone uses the library by just including it, but that doesn't matter in test-only code.)

Noticed when looking into https://github.com/bitcoin-core/secp256k1/pull/1489.

**Comment by fanquake** [comment]
What is left to do here post #1533 ?
