### ISSUE TITLE
ci: macOS brew outdated / upgrade macOS version?  

### ISSUE THREAD

**Issue by real-or-random** [bitcoin-core/secp256k1#1536]
CI is currently failing on macOS. This should be resolved once the GitHub Actions image is updated to have brew 4.3.1, which has the fix (https://github.com/Homebrew/brew/pull/17336). The images are updated every week, so the issue should just disappear in a few days.

_Originally posted by @real-or-random in https://github.com/bitcoin-core/secp256k1/issues/1517#issuecomment-2124806897_

**Comment by real-or-random** [comment]
> The images are updated every week, so the issue should just disappear in a few days.

Apparently, the last update of the macOS 12 build is almost two weeks ago, see https://github.com/actions/runner-images?tab=readme-ov-file#available-images. Maybe that's a good opportunity to move to macOS 13 or 14. Valgrind shouldn't be a problem: https://github.com/LouisBrunner/valgrind-macos?tab=readme-ov-file#status

@hebasto Any thoughts on this?

**Comment by hebasto** [comment]
They started updating images yesterday: https://github.com/actions/runner-images/tags. So I'm expecting an updated macOS 12 image this week as well.

> Maybe that's a good opportunity to move to macOS 13 or 14.

The free macOS 14 image has arm64 architecture. Please see https://github.com/bitcoin-core/secp256k1/pull/1488.

**Comment by hebasto** [comment]
> They started updating images yesterday: https://github.com/actions/runner-images/tags. So I'm expecting an updated macOS 12 image this week as well.

https://github.com/actions/runner-images/releases/tag/macos-12/20240527.4

**Comment by real-or-random** [comment]
The image has been updated, and I've triggered reruns for all PRs that still had a failing status due to this.
