### ISSUE TITLE
tests: Lower default of iters to 4 (but keep higher on CI)

### ISSUE THREAD

**Issue by real-or-random** [bitcoin-core/secp256k1#1561]
See discussion at https://gnusha.org/secp256k1/2024-07-01.log, also mentioned in https://github.com/bitcoin-core/secp256k1/issues/1549.

**Comment by jonasnick** [comment]
@sipa said the following in the discussion:

> < sipa> i don't think that running at more than 1 has ever actually contributed to a bug being found :p

I don't agree. For example, there are tests that should draw random group elements with an even Y coordinate in one iteration and an odd one in another to test both code paths. Default iteration number of 4 will make 1 in 16 such tests useless.

**Comment by jonasnick** [comment]
Should have spelled this out more clearly: I have found bugs during development in code that was only correct  if the Y coordinates of random group elements had a specific parity :/

**Comment by jonasnick** [comment]
See also https://github.com/bitcoin-core/secp256k1/issues/1036
