### ISSUE TITLE
Conan package "secp256k1" does not exist

### ISSUE THREAD

**Issue by selevit** [bitcoin-core/secp256k1#1597]
Hey, any plans to add the library into [Conan Center](https://conan.io/center/)? So it can be installed via the Conan package manager?

**Comment by real-or-random** [comment]
> Hey, any plans to add the library into [Conan Center](https://conan.io/center/)? So it can be installed via the Conan package manager?

No plans on our side currently. But if you're willing to do it and maintain it, I'm sure we're able to answer any build-related questions and/or take a brief look at the thing. Others tried that in the past, so here are some starting points:
https://github.com/Gigamonkey-BSV/secp256k1-conan-recipe
https://github.com/maurodelazeri/conan-secp256k1
(I haven't looked at them, so I can't endorse anything.)

Note that we offer *both* autotools and CMake builds, so you can pick whatever suits best. (I assume CMake is the modern option. :))

**Comment by real-or-random** [comment]
> Lets keep this ticket open, maybe someone (or me eventually) will be able to maintain the Conan package.

I prefer to close it because no action is planned on our side. But this can and should prevent noone from creating a Conan package or commenting in this issue in the future.
