### ISSUE TITLE
Error when installing via pip install secp256k1 

### ISSUE THREAD

**Issue by dragonked2** [bitcoin-core/secp256k1#1643]
Error when installing via pip install secp256k1 
Collecting secp256k1
  Downloading secp256k1-0.14.0.tar.gz (2.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.4/2.4 MB 3.8 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [1 lines of output]
      'pkg-config' is required to install this package. Please see the README for details.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

its been for years im facing this issue any solution ?

**Comment by real-or-random** [comment]
This is the repository for the C library libsecp256k1. The python package secp256k1, which provides bindings for the C library, can be found at https://github.com/rustyrussell/secp256k1-py.
