### ISSUE TITLE
Documentation should provide example callers.

### ISSUE THREAD

**Issue by gmaxwell** [bitcoin-core/secp256k1#184]
We've seen some people attempting to use the library calling into random internal functions. That should be harder to do now... but now that the basic signature interface is relatively safe to use (as such things go) there should be some easy copy and paste examples for correct usage.

**Comment by jonasnick** [comment]
As an example we have someting like this in secp256k1-zkp to demonstrate musig: https://github.com/ElementsProject/secp256k1-zkp/blob/secp256k1-zkp/src/modules/musig/example.c

**Comment by NicholasFarrow** [comment]
For anyone else interested in how to generate keys using this library, feel free to checkout my [Bitcoin vanity address generator](https://github.com/NicholasFarrow/niceBit/) which I think provides a short and [reasonably well commented example](https://github.com/NicholasFarrow/niceBit/blob/master/niceBit.c) of how to generate private and public key pairs.

**Comment by jonasnick** [comment]
I'd suggest to add a short and well documented example source file for every module and build and run it as part of `make check`. We can list the modules in the README and from there link to the examples and include files for more documentation.
