### ISSUE TITLE
Ought secp256k1_ec_privkey_import() also indicate whether the key is compressed? 

### ISSUE THREAD

**Issue by afk11** [bitcoin-core/secp256k1#246]
When exporting a private key, the compressed flag is required to create the correct DER key. 

I noticed that `secp256k1_ec_privkey_import()` only takes a pointer for a secret key. I think it should take an `int *` to inform whether the key should be serialized to its compressed representation. 

I'll try have a look see if it's a straightforward change, though my C isn't the best. Does this seem worthwhile, or was there perhaps a reason it doesn't do this?

**Comment by sipa** [comment]
The DER private key import/export are only really intended for compatibility reasons, and they should probably have big comments explaining the limitations.

What you are saying is not necessary for its use in Bitcoin, but I wouldn't be opposed to having it, if others find it useful.

**Comment by afk11** [comment]
I see - I haven't looked much at it's use in Bitcoin Core. I ask because without it, other implementations must track state elsewhere. Being able to import the DER key and immediately do `secp256k1_ec_pubkey_create(..., seckey, compressed)`
