### ISSUE TITLE
Port for FreeBSD

### ISSUE THREAD

**Issue by tuaris** [bitcoin-core/secp256k1#253]
I know this is not officially released yet but I have made a FreeBSD port skeleton that I would like to submit into the official ports tree since some other projects are starting to require it as a dependency..  

https://github.com/tuaris/secp256k1-freebsd

Is there a specific commit I should reference or is the latest okay?
What would a proper version number be at this point?

**Comment by gmaxwell** [comment]
Please do not.  This is an experimental, unreleased, research project which is actively in flux. None of its interfaces are stable and have completely changed as of a few weeks ago.

Software should not be using this as an external dependency at this time. Anyone who is is potentially putting their users in danger.

**Comment by tuaris** [comment]
I agree and thank you for the feedback.  There are some 'altcoins' currently using this and was wondering as well.  

I will hold off on this for now and continue to watch.

**Comment by gmaxwell** [comment]
Can you email me (greg@xiph.org) and point me to them so I can go apply a cluestick?

**Comment by tuaris** [comment]
Done.
