### ISSUE TITLE
Use MAX/MIN over cumbersome statements

### ISSUE THREAD

**Issue by dcousens** [bitcoin-core/secp256k1#268]
Reference: https://github.com/bitcoin/secp256k1/pull/266#discussion_r34113224

May be relevant to a few sections,  but this is generally a much more readable pattern.

**Comment by sipa** [comment]
PR welcome ;)

**Comment by dcousens** [comment]
@sipa of course,  but,  obviously priorities.   May be try out the `help wanted` tag?  :P

**Comment by gmaxwell** [comment]
Macro based MAX/MIN  ends up evaluating the arguments multiple times; if they have side-effects that can be surprising. Just a thought.

**Comment by dcousens** [comment]
So many other fish to fry
