### ISSUE TITLE
Visual Studio build

### ISSUE THREAD

**Issue by chfast** [bitcoin-core/secp256k1#327]
I've seen Visual Studio related PRs. Is there any working Visual Studio build? What about big number implementation? @ximinez?

**Comment by sipa** [comment]
There is no need for a bignum implementation. It gives a mild performance boost to have gmp for computing modular inverses, but you can compile without. Furthermore, @apoelstra is working on a native fast modular inverse, so we have drop the GMP requirement entirely.

**Comment by chfast** [comment]
Thanks, good to know that.
Last time I was playing with cmake (#315) I had to define `USE_NUM_GMP`.

**Comment by apoelstra** [comment]
@chfast defining `USE_NUM_NONE` should have also worked for you.

**Comment by chfast** [comment]
Yes, it works.

**Comment by ZeroXn** [comment]
How can I include this in my visual studio project?
I have included the header files, but not sure how i actually compile the library?

So far i have only added the include folder to my additional include directories, im my project properties, and get a `LNK2019 unresolved external symbol _secp256k1_context_create referenced in function` when i try and compile my project.

Any hints would be great! Thanks!
`

**Comment by evoskuil** [comment]
@ZeroXn  see: https://github.com/evoskuil/secp256k1/tree/version4/builds/msvc
