### ISSUE TITLE
Implement secp256k1_ecdsa_signature_serialize and  int secp256k1_ecdsa_signature_parse

### ISSUE THREAD

**Issue by rustyrussell** [bitcoin-core/secp256k1#333]
Non-DER versions, which just fill in 64 bits in some canonical order.

Alternately: make the opaque structure a canonical order.

**Comment by sipa** [comment]
See my laxder branch, it also adds those. I'll PR when I either decide to
split it off from the DER rework, or tests for that are finished.

**Comment by rustyrussell** [comment]
Yep, looks good!  Please document the serialize format (at a glance, it's 32 byte unsigned BE r value followed by 32 byte unsigned BE s value).

I'd still like a "is_normalized" or "is_canonical" for the s-value test BTW, but I can implement my own with these.

**Comment by sipa** [comment]
Working on those!

**Comment by sipa** [comment]
Fixed by #334.
