### ISSUE TITLE
ldconfig does not update the library cache on make install

### ISSUE THREAD

**Issue by g-p-g** [bitcoin-core/secp256k1#336]
I see that a call to `ldconfig -n /usr/local/lib` happens during `make install`, but that doesn't cause the shared library cache to be updated as `-n` implies `-N` (which instructs ldconfig to not rebuild the cache):

```
$ sudo ldconfig -n /usr/local/lib
$ ldconfig -p | grep secp
$ sudo ldconfig /usr/local/lib
$ ldconfig -p | grep secp
    libsecp256k1.so.0 (libc6,x86-64) => /usr/local/lib/libsecp256k1.so.0
    libsecp256k1.so (libc6,x86-64) => /usr/local/lib/libsecp256k1.so
```

**Comment by gmaxwell** [comment]
AFAIK it's not normal for make install to run ldconfig for cache rebuilding.  There is some discussion at https://github.com/esnet/iperf/issues/153  which suggests that attempt to do so is fraught with issues.

**Comment by gmaxwell** [comment]
Closing this since it's inactive and I _think_ nothing needs to be done.
