### ISSUE TITLE
Building lib-secp256k1 fails due to file permissions

### ISSUE THREAD

**Issue by quend** [bitcoin-core/secp256k1#370]
the pip installer for c-secp256k1 fails when trying to build lib-secp256k1.

example:
sh -c cd lib-secp256k1; ./autogen.sh
sh: 1: ./autogen.sh: Permission denied

fix:
manually mark the autogen file as executable

**Comment by Miladinho** [comment]
chmod 755 * should work

**Comment by gmaxwell** [comment]
It's currently marked executable in the repository.
