### ISSUE TITLE
ecmult_static_context.h does not exist

### ISSUE THREAD

**Issue by user8547** [bitcoin-core/secp256k1#394]
ecmult_gen_impl.h:
```
#ifdef USE_ECMULT_STATIC_PRECOMPUTATION
#include "ecmult_static_context.h"
#endif
```
The file "ecmult_static_context.h" does not exist.

**Comment by fanatid** [comment]
```
./autogen.sh
./configure
make src/ecmult_static_context.h
```
https://github.com/bitcoin-core/secp256k1/blob/6875b013e6012b83bf646b533e866a2b58b8d48c/Makefile.am#L132

**Comment by user8547** [comment]
Clear, thank you!

**Comment by apoelstra** [comment]
You shouldn't have to make that file individually. @user8547 does simply re-running autogen.sh and configure fix it?

**Comment by user8547** [comment]
Without
```
make src/ecmult_static_context.h
```
the ecmult_static_context.h is not produced.

I am not sure whether it should be produced by autogen.sh and configure.
I am compiling against libsecp256k1 statically therefore I missed that ecmult_static_context.h is generated by make.

**Comment by apoelstra** [comment]
Does `make` by itself produce the file?

**Comment by user8547** [comment]
Yes, it does.

**Comment by apoelstra** [comment]
OK, great. This is expected behaviour.
