### ISSUE TITLE
update warning msg

### ISSUE THREAD

**Issue by raedah** [bitcoin-core/secp256k1#395]
"This library is a work in progress and is being used to research best practices. Use at your own risk."

It seems it has moved beyond this mark and is used in production now.

**Comment by apoelstra** [comment]
We aren't going to remove the warning because people have, in fact, ignored it :)

**Comment by raedah** [comment]
By people, you mean, the bitcoin core project, of which this project is a sub-project?

**Comment by gmaxwell** [comment]
@raedah The usage in Bitcoin Core is very specialized, does not use all the features and optimizations, and is also _by_ the same people here.  Saying something is ready for use in a particular context does not imply that is ready for anything else in particular.
