### ISSUE TITLE
Parameter ordering of some field and group functions contradict API standards

### ISSUE THREAD

**Issue by llamasoft** [bitcoin-core/secp256k1#406]
I'd like to apologize in advance if this has been addressed already.  I couldn't find mention of it in the issue tracker, so I thought I'd mention it.  
The API parameter ordering guide outlined in [secp256k1.h](https://github.com/bitcoin-core/secp256k1/blob/master/include/secp256k1.h#L10-L23) say that array lengths should always _follow_ the argument whose length they refer to.  

The following internal functions accept a length parameter before the object they refer to:
- [`secp256k1_fe_inv_all_var`](https://github.com/bitcoin-core/secp256k1/blob/master/src/field.h#L110-L113)
- [`secp256k1_ge_set_all_gej_var`](https://github.com/bitcoin-core/secp256k1/blob/master/src/group.h#L67-L68)
- [`secp256k1_ge_set_table_gej_var`](https://github.com/bitcoin-core/secp256k1/blob/master/src/group.h#L70-L73)
- [`secp256k1_ge_globalz_set_table_gej`](https://github.com/bitcoin-core/secp256k1/blob/master/src/group.h#L75-L80)

I know these aren't API functions so the standards may not apply here, but it may be worth reordering their parameters for consistency's sake.

**Comment by apoelstra** [comment]
Thanks for looking through this! Agreed, these functions should be consistent with the public ones (though in general, the public API guarantees do not apply to internal functions).

**Comment by llamasoft** [comment]
I've added a pull request (#407) to rearrange the parameter order for the above functions plus two extra.

**Comment by gmaxwell** [comment]
(PR was merged)
