### ISSUE TITLE
Compiler optimizing out clearing of sensitive buffers

### ISSUE THREAD

**Issue by llamasoft** [bitcoin-core/secp256k1#418]
As noted from Issue #414, it appears that compilers are optimizing out the clearing of sensitive memory.  
There are a few ways to work around these shortcomings, discussed in [CWE-14](https://cwe.mitre.org/data/definitions/14.html) and [MSC06-C](https://www.securecoding.cert.org/confluence/display/c/MSC06-C.+Beware+of+compiler+optimizations).

Options include:
- Casting to `volatile` during assignment
- Rolling your own `memset_s` or using C11's version
- Temporarily disabling optimization using `#pragma` (probably not portable)

**Comment by real-or-random** [comment]
I think this is a duplicate of #185.
