### ISSUE TITLE
 node-gyp rebuild fails

### ISSUE THREAD

**Issue by haiqu** [bitcoin-core/secp256k1#420]
Environment: Windows 7 Home Premium, nodejs v6.7.0, node-gyp v3.4.0, npm v3.10.8

Trying to build metamask-plugin and the build fails with an error that suggest a script fault in sec256k1

C:\Users\Rob\metamask-plugin\node_modules\eth-store\node_modules\secp256k1>if not defined npm_config_node_gyp (node "C:\Users\Rob\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
'.' is not recognized as an internal or external command,
operable program or batch file.
gyp: Call to './utils/has_lib.sh gmpxx && ./utils/has_lib.sh gmp' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\Rob\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Rob\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Rob\metamask-plugin\node_modules\eth-store\node_modules\secp256k1

**Comment by apoelstra** [comment]
This looks like a node issue; this project does not use node and is unaffiliated with the node project that binds to this library, so we cannot help you, sorry. Please open an issue there.

Thanks for the submission.

**Comment by haiqu** [comment]
Apologies for the spam. The report has been sent now to the maintainers of secp256k.
