### ISSUE TITLE
schnorr sign question

### ISSUE THREAD

**Issue by fanatid** [bitcoin-core/secp256k1#423]
In schnorr sign `s` is not checked that value is zero https://github.com/bitcoin-core/secp256k1/blob/04c8ef36ad35e846ac27157021a78f79465f2a22/src/modules/schnorr/schnorr_impl.h#L98-L102
but we should, is not it?

**Comment by sipa** [comment]
key and h are checked for zero. if neither of them is, their multiplication
can't be zero either.

**Comment by fanatid** [comment]
haha, of course
