### ISSUE TITLE
Cannot build on Debian stretch

### ISSUE THREAD

**Issue by possientis** [bitcoin-core/secp256k1#429]
I have never reported an issue here before. I hope I am not infringing on some important protocol I should know about. Please feel free to suggest ways of improving my reports going forward.    

    $ uname -a
    Linux front 4.8.0-1-amd64 #1 SMP Debian 4.8.7-1 (2016-11-13) x86_64 GNU/Linux

    $ ./autogen.sh
    ...

    $ ./configure
    ...

    $ make
    gcc -I. -g -O2 -Wall -Wextra -Wno-unused-function -c src/gen_context.c -o gen_context.o
    gcc gen_context.o -o gen_context
    ./gen_context
      CC       src/libsecp256k1_la-secp256k1.lo
      CCLD     libsecp256k1.la
    /usr/bin/ar: `u' modifier ignored since `D' is the default (see `U')
      CC       src/tests-tests.o
    src/tests.c: In function ‘test_ecdsa_der_parse’:
    src/tests.c:3702:52: error: dereferencing pointer to incomplete type ‘ECDSA_SIG 
    {aka struct ECDSA_SIG_st}’  valid_openssl = !BN_is_negative(sig_openssl->r) &&
    !BN_is_negative(sig_openssl->s) && BN_num_bits(sig_openssl->r) > 0 &&
    BN_num_bits(sig_openssl->r) <= 256 && BN_num_bits(sig_openssl->s) > 0 &&
     BN_num_bits(sig_openssl->s) <= 256;
                                                ^~
    Makefile:1050: recipe for target 'src/tests-tests.o' failed
    make: *** [src/tests-tests.o] Error 1

However, everything works fine (including `make check`) with:
  
    $ ./configure --enable-openssl-tests=no

**Comment by apoelstra** [comment]
Can you confirm that the latest master (since #433 was merged) compiles correctly?

Thanks for the report.

**Comment by possientis** [comment]
Master branch all good for me

**Comment by TheWizIL** [comment]
> $uname
Linux Server22929-server 4.9.0-4-amd64 #1 SMP Debian 4.9.51-1 (2017-09-28) x86_64 GNU/Linux

Problem still appear. 
Work when:
> $ ./configure --enable-openssl-tests=no
