### ISSUE TITLE
Shared library broken on MinGW

### ISSUE THREAD

**Issue by mmgen** [bitcoin-core/secp256k1#430]
This stub compiles, links and runs on Linux

        #include <stdio.h>
        #include <secp256k1.h>
        
        int main()
        {
        	static secp256k1_context *ctx = NULL;
        	ctx = secp256k1_context_create(SECP256K1_CONTEXT_SIGN);
        	return 1;
        }

but produces the following linking error under MinGW:

        $ gcc my.c -lsecp256k1 -I/usr/local/include -L/usr/local/lib
        C:/msys/local/lib/libsecp256k1.a(libsecp256k1_la-secp256k1.o): In function `secp256k1_num_set_bin':
        c:\build\secp256k1/src/num_gmp_impl.h:49: undefined reference to `_imp____gmpn_set_str'
        C:/msys/local/lib/libsecp256k1.a(libsecp256k1_la-secp256k1.o): In function `secp256k1_num_mod_inverse':
        c:\build\secp256k1/src/num_gmp_impl.h:128: undefined reference to `_imp____gmpn_gcdext'
        C:/msys/local/lib/libsecp256k1.a(libsecp256k1_la-secp256k1.o): In function `secp256k1_num_get_bin':
        c:\build\secp256k1/src/num_gmp_impl.h:34: undefined reference to `_imp____gmpn_get_str'
        C:/msys/local/lib/libsecp256k1.a(libsecp256k1_la-secp256k1.o): In function `_gmpn_sub':
        c:/mingw/include/gmp.h:2097: undefined reference to `_imp____gmpn_sub_n'
        collect2.exe: error: ld returned 1 exit status

The undefined symbols:

        $ objdump.exe -t /usr/local/lib/libsecp256k1.a | grep imp_
        [116](sec  0)(fl 0x00)(ty   0)(scl   2) (nx 0) 0x00000000 __imp___iob
        [117](sec  0)(fl 0x00)(ty   0)(scl   2) (nx 0) 0x00000000 __imp____gmpn_set_str
        [118](sec  0)(fl 0x00)(ty   0)(scl   2) (nx 0) 0x00000000 __imp____gmpn_gcdext
        [119](sec  0)(fl 0x00)(ty   0)(scl   2) (nx 0) 0x00000000 __imp____gmpn_get_str
        [120](sec  0)(fl 0x00)(ty   0)(scl   2) (nx 0) 0x00000000 __imp____gmpn_sub_n

**Comment by sipa** [comment]
Does it work when you add `-lgmp` to the command line? I'm surprised it works in Linux without that.

**Comment by mmgen** [comment]
That did the trick! Thanks, Pieter! It does work in Linux without that, by the way.

**Comment by sipa** [comment]
Maybe you just compiled in linux without gmp dependency? (--without-bignum, or just no libgmp developer files available?)

**Comment by mmgen** [comment]
No extra options at all, just ./configure and make.

**Comment by sipa** [comment]
Right, but your Linux build environment may just not have libgmp-dev, in
which case configure will automatically build without libgmp support.

**Comment by mmgen** [comment]
I rebuilt and reinstalled the library; configure enables libgmp. Stub still compiles OK without -lgmp though. I think this is because Linux allows unresolved symbols in shared libraries.

        $ objdump -t /usr/local/lib/libsecp256k1.a | grep gmp
        0000000000000000         *UND*  0000000000000000 __gmpn_set_str
        0000000000000000         *UND*  0000000000000000 __gmpn_gcdext
        0000000000000000         *UND*  0000000000000000 __gmpn_get_str
        0000000000000000         *UND*  0000000000000000 __gmpn_sub_n

**Comment by aparesse** [comment]
@mmgen @sipa how to solve this in Mac OS X? thanks

**Comment by aparesse** [comment]
@mmgen @sipa  and the using compiler is clang

**Comment by mmgen** [comment]
@aparesse no idea, sorry
