### ISSUE TITLE
undefined reference to `pthread_once'

### ISSUE THREAD

**Issue by ghost** [bitcoin-core/secp256k1#434]
Hi,

I have managed to correct the previous errors but now get the above, any idea how to correct this?

**Comment by rg83rg** [comment]
do i need to edit the make file  with -L/lib64 -lpthread after flags, if so can you tell me how to do this exactly, thanks

**Comment by sipa** [comment]
libsecp256k1 has no threading whatsoever. What are you doing to get this error?

**Comment by gmaxwell** [comment]
No follow up from user, github deleted the account.  Feel free to open a new issue if required.
