### ISSUE TITLE
Erro when ./autogen.sh running Ubuntu 14.04

### ISSUE THREAD

**Issue by rg83rg** [bitcoin-core/secp256k1#435]
ubuntu@ubuntu:~/secp256k1$ ./autogen.sh
autom4te: cannot create autom4te.cache: No such file or directory
aclocal: error: echo failed with exit status: 1
autoreconf: aclocal failed with exit status: 1

**Comment by apoelstra** [comment]
It looks like you need install autoconf (and probably some other autotools).
