### ISSUE TITLE
Clang fsanitize=safe-stack RFC6979 miscompile issue

### ISSUE THREAD

**Issue by laanwj** [bitcoin-core/secp256k1#445]
There is a miscompile issue with LLVM 4.0 safe-stack and the [secp256k1_rfc6979_hmac_sha256_generate](https://github.com/bitcoin-core/secp256k1/blob/master/src/hash_impl.h#L235) function. This results in invalid deterministic signatures, (luckily) causing both the secp256k1 and bitcoin tests to fail.

I'm fairly sure that this is a clang bug, although it's curious that it only seems to affect that function (and not any other tested use of SHA256, for example). In any case FYI this is being investigated here: https://github.com/NuxiNL/cloudabi-ports/issues/30

**Comment by laanwj** [comment]
Update: this problem is confirmed to exist on LLVM 4.0-rc3, and also on the SVN trunk.
A bug has been filed: https://bugs.llvm.org//show_bug.cgi?id=32143

Until fixed I'd strongly suggest not to use stafestack santiize with secp256k1.

**Comment by jonasschnelli** [comment]
This bug is now active in LLVM 4.0 (release) and will very likely be fixed in 4.0.1

**Comment by laanwj** [comment]
This is fixed upstream, closing.
