### ISSUE TITLE
Windows target

### ISSUE THREAD

**Issue by ofek** [bitcoin-core/secp256k1#451]
How do you build this for (or on) Windows?

**Comment by chfast** [comment]
I'm using CMake to build it. E.g. https://github.com/ethereum/cpp-ethereum/blob/develop/cmake/secp256k1/CMakeLists.txt or #315.

**Comment by ofek** [comment]
I've figured it out https://github.com/ofek/coincurve/blob/master/.travis/prepare_windows_build.sh / https://github.com/ofek/coincurve/blob/master/.travis/build_windows_wheels.sh

Though, I don't know how to build libgmp for Windows for use with libsecp256k1.

**Comment by chfast** [comment]
You can configure libsecp256k1 not to use GMP at all. Option is `--with-bignum=none`.

**Comment by ofek** [comment]
Oh yes but I'd like to use it. Have you tried building for Windows with gmp?

**Comment by chfast** [comment]
I don't think you can build GMP with Visual Studio. I suggest using MPIR instead. It is compatible with GMP.

**Comment by ofek** [comment]
Looks interesting, thanks!

**Comment by chfast** [comment]
I'm also trying to provide CMake support for it. https://github.com/wbhart/mpir/pull/215.

**Comment by laanwj** [comment]
Including secp256k1 in any project is easy as it's a single-file library. Though if you use another build system make sure that the correct defines for your platform are set, either in `libsecp256k1-config.h` (and `HAVE_CONFIG_H` set) or otherwise.

**Comment by kroggen** [comment]
Just sharing [another method](https://github.com/aergoio/secp256k1-vrf/blob/master/.github/workflows/build.yml) using GitHub Actions and Visual C
