### ISSUE TITLE
LDFLAGS not used for gen_context

### ISSUE THREAD

**Issue by ysangkok** [bitcoin-core/secp256k1#469]
On systems where additional CFLAGS or LDFLAGS are needed, they are not passed to gcc when building gen_context.

They need to be passed from bitcoin core's build system. I am already supplying bitcoin core's configure with the LDFLAGS.

https://github.com/bitcoin/bitcoin/blob/6adc3a37324caa07015368bfe8529e1964366eef/src/secp256k1/Makefile.am#L157

**Comment by real-or-random** [comment]
That should be fixed with a34bcaadf14442b86a5de120d4afd131f910d73d. Note that the variable is `LDFLAGS_FOR_BUILD` and not `LDFLAGS` for this specific case.
