### ISSUE TITLE
Tag for bitcoin releases

### ISSUE THREAD

**Issue by sipsorcery** [bitcoin-core/secp256k1#481]
Is this the repo used with official bitcoin releases? If so is there any way to match tags on the bitcoin repo with this repo? 

I'm trying to create some deterministic build scripts and it would be helpful to be no at what point the secp256k1 repo was built for bitcoin.

**Comment by AndreMiras** [comment]
Yes this is a nice project and I'm also using it for https://github.com/AndreMiras/EtherollApp and https://github.com/AndreMiras/PyWallet, both have Travis continuous integration testing and having reproducible build would help. At the moment I freeze by commit hash, but it would be nice to have some releases.
Don't wait too much to have the perfect initial release, just [release early, release early](https://en.wikipedia.org/wiki/Release_early,_release_often) and you would be fine :smiley: 
This library is already used in many projects anyway.

If you don't know how to tag it, don't bother with semantic versioning and just go with the `vYYYYMMDD` format, Ubuntu-style-ish.

**Comment by gmaxwell** [comment]
@sipsorcery  that is a non-issue: Bitcoin Core includes the library itself.  You do not need to do anything with this repository for Bitcoin's reproducability.  (and, indeed, the builds there are reproducable and have been for many years).
