### ISSUE TITLE
install secp256k1

### ISSUE THREAD

**Issue by gwh709394** [bitcoin-core/secp256k1#483]
Hello All
I cannot install secp256k1, could anyone help me? I got the message when I run 'autogen.sh'.
`/usr/local/bin/glibtoolize: line 406: /usr/local/Library/ENV/4.3/sed: No such file or directory
/usr/local/bin/glibtoolize: line 2513: /usr/local/Library/ENV/4.3/sed: No such file or directory
/usr/local/bin/glibtoolize: line 2513: /usr/local/Library/ENV/4.3/sed: No such file or directory
/usr/local/bin/glibtoolize: line 3601: /usr/local/Library/ENV/4.3/sed: No such file or directory
/usr/local/bin/glibtoolize: line 3845: /usr/local/Library/ENV/4.3/sed: No such file or directory
/usr/local/bin/glibtoolize: line 861: /usr/local/Library/ENV/4.3/sed: No such file or directory
: putting auxiliary files in '.'.
: copying file './ltmain.sh'
/usr/local/bin/glibtoolize: line 3771: /usr/local/Library/ENV/4.3/sed: No such file or directory
configure.ac:10: error: required file 'build-aux/ltmain.sh' not found
autoreconf: automake failed with exit status: 1`

my machine is macOS Sierra .

**Comment by JackPickering** [comment]
sudo apt-get install autoconf autogen
