### ISSUE TITLE
Generate keys

### ISSUE THREAD

**Issue by TooLazyy** [bitcoin-core/secp256k1#514]
Hi. How could i just generate key pair (private and public)?
Cannot find any examples of usage for such primitive task.

**Comment by afk11** [comment]
There is no private key generation function in this library, you generate it elsewhere. To create the public key, use secp256k1_ec_pubkey_create
https://github.com/bitcoin-core/secp256k1/blob/cd329dbc3eaf096ae007e807b86b6f5947621ee3/include/secp256k1.h#L526

**Comment by businessintegrator** [comment]
Hi
I can generate mass keys in Java ifyou specify your expected format.
Best Regards
Tiaray RAFARALAHITSIMBA

**Comment by afk11** [comment]
@businessintegrator that offer is unwelcome here.

**Comment by NicholasFarrow** [comment]
For anyone else interested in how to generate keys using this library, feel free to checkout my [Bitcoin vanity address generator](https://github.com/NicholasFarrow/niceBit/) which I think provides a short and [reasonably well commented example](https://github.com/NicholasFarrow/niceBit/blob/master/niceBit.c) of how to generate private and public key pairs.
