### ISSUE TITLE
Enable module recovery by default

### ISSUE THREAD

**Issue by MavenRain** [bitcoin-core/secp256k1#519]
This is required for building libbitcoin independently, but is currently disabled by default.  Turning this default on will provide a better customer experience for developers attempting to quickly building their bitcoin development environment.

**Comment by BernardoDeLaPlaz** [comment]
Agreed. This would be a good change.

**Comment by apoelstra** [comment]
Closing this. People should not use recoverable signatures in basically any application -- their patent story is questionable and they cannot be batch-validated.

**Comment by dcousens** [comment]
@apoelstra doesn't `bitcoind` use it?

**Comment by apoelstra** [comment]
Yes, but only for historical reasons, in the signmessage API which will be replaced by BIP322 or something similar.

**Comment by apoelstra** [comment]
I understand that it may be necessary for Bitcoin-related projects such as libbitcoin. However we still want to ensure that people using the module know they are using something odd.

**Comment by dcousens** [comment]
Maybe note this questionable encumberance in the README?

**Comment by dcousens** [comment]
@evoskuil what is your thoughts around this?

**Comment by dcousens** [comment]
@apoelstra this isn't a new thought
https://bitcointalk.org/index.php?topic=940436.msg10306479#msg10306479
https://bitcoin.stackexchange.com/questions/75322/why-do-we-need-public-key-as-part-of-witness-in-p2wpkh-transactions


@gmaxwell have you or anyone reached out to Certicom?  Is it actually infringing or no?
@laanwj what is your thoughts around `bitcoind`?

Why not simply remove it?

**Comment by evoskuil** [comment]
no opinion
