### ISSUE TITLE
No module names secp256k1._libsecp256k1

### ISSUE THREAD

**Issue by JackPickering** [bitcoin-core/secp256k1#520]
When installing the packages necessary to run this library on a Debian server running a py3 VM, it produces the error: 

ax1-staging >     ----- Python Traceback -----                                                                                                                    
ax1-staging >     File "ecdsa_imp/lib/python3.6/site-packages/ecdsa.py", line 6, in <module>
ax1-staging >       from sign import sign                                                                                                                          
ax1-staging >     File "/var/www/ico_test/source/ecdsa_imp/lib/python3.6/site-packages/sign.py", line 8, in <module>                                               
ax1-staging >       from secp256k1 import PrivateKey                                                                                                               
ax1-staging >     File "/var/www/ico_test/source/ecdsa_imp/lib/python3.6/site-packages/secp256k1/__init__.py", line 5, in <module> 
ax1-staging >       from ._libsecp256k1 import ffi, lib                                                                                                            
ax1-staging >   traceback: 'Traceback (most recent call last):\n  File "ecdsa_imp/lib/python3.6/site-packages/ecdsa.py", line 6, in <module>\n    from sign      
 import sign\n  File "/var/www/ico_test/source/ecdsa_imp/lib/python3.6/site-packages/sign.py", line 8, in <module>\n    from secp256k1 import PrivateKey\n  File "/var/www/ico_test/source/ecdsa_imp/lib/python3.6/site-packages/secp256k1/__init__.py", line 5, in <module>\n    from ._libsecp256k1 import ffi, lib\nImportError : No module named \'secp256k1._libsecp256k1\'\n',                                                                                                                 
ax1-staging >   executable: '/usr/bin/python3',````

This library is supposed to be included when running the ./autogen command however, we have tried installing it, installing the binary version, searching for the library and it is there. 

Any idea as to how to fix this?

**Comment by sipa** [comment]
We don't have Python bindings.

**Comment by wey1288** [comment]
Sorry for inconveniences brought you all.

Have a nice day)
27 Мар 2018 г. 16:41 пользователь "Jack Pickering" <notifications@github.com>
написал:
