### ISSUE TITLE
Use java version in my project

### ISSUE THREAD

**Issue by goral09** [bitcoin-core/secp256k1#534]
Hi all,

I would like to make use of java's version of your secp256k1. How can I add this as dependency to my JVM project? I think simply copying the files would work but it's probably not industry standard for doing that kind of stuff.

**Comment by jonasnick** [comment]
Sorry for the late reply, but we have removed the JNI bindings since you opened this issue. See the corresponding PR https://github.com/bitcoin-core/secp256k1/pull/682 for alternatives.
