### ISSUE TITLE
Source for `secp256k1_ecmult_gen` algorithm?

### ISSUE THREAD

**Issue by ubamnow404** [bitcoin-core/secp256k1#535]
I have been working on understanding this implementation of secp256k1.

Is `secp256k1_ecmult_gen` essentially Algorithm 13.6 (page 306) from Cohen and Frey, _Handbook of Elliptic and Hyperelliptic Curve Cryptography_?

**Comment by gmaxwell** [comment]
I don't have that book, but the algorithm in secp256k1_ecmult_gen  is trivial: There is a precomputed table of xG where x is every digit in the base-16 representation of the scalar (so the table has 16 * 64 entries).  It just reads out the correct entries and adds them up, no doubling is even used at all.
