### ISSUE TITLE
Distributing binary licenses

### ISSUE THREAD

**Issue by DesWurstes** [bitcoin-core/secp256k1#537]
Which licenses to distribute with the compiled secp256k1? `COPYING`says Pieter Wuille, some files say Andrew Poelstra, [some files](https://github.com/bitcoin-core/secp256k1/blob/452d8e4d2a2f9f1b5be6b02e18f1ba102e5ca0b4/src/ecmult_impl.h#L2) say the names of contributors.

Is there anything I can do other than reading all the files' copyright texts to find the whole list of contributors?

**Comment by apoelstra** [comment]
Maybe we should change `COPYING` to say "The Bitcoin Core developers" or "the libsecp256k1 developers" to match Core?

**Comment by gmaxwell** [comment]
Please don't do that. This is a bad practice in Bitcoin Core.

**Comment by apoelstra** [comment]
Closing as I don't think sipa or I have any strong feelings, so I expect no further progress on this.
