### ISSUE TITLE
how to get r, s, v out of signature?

### ISSUE THREAD

**Issue by BernardoDeLaPlaz** [bitcoin-core/secp256k1#544]
I see in secp256k1/include/secp256k1.h

 *  The signature must consist of a 32-byte big endian R value, followed by a
 *  32-byte big endian S value. If R or S fall outside of [0..order-1], the
 *  encoding is invalid. R and S with value 0 are allowed in the encoding.
 
I take it this means that if I generate a signature in a _secp256k1_pubkey_ I can look in the first 32 bytes to find R and the next 32 bytes to find S.

...but how can I find 'v' ?

Thanks.

**Comment by BernardoDeLaPlaz** [comment]
Ah...I have to use the functions in secp256k1_recovery.h to convert my signature to a recovery signature, I think?

**Comment by sipa** [comment]
You can't convert a normal signature to a recoverable signature. You can try recid=0, recid=1, recid=2, recid=3 though, and see which one recovers your expected public key.
