### ISSUE TITLE
cannot compile (make (build-aux) ERROR)

### ISSUE THREAD

**Issue by nerotiger** [bitcoin-core/secp256k1#556]
-------------------------------------------------------------------

> libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, 'build-aux'.
> libtoolize: copying file 'build-aux/ltmain.sh'
> libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'build-aux/m4'.
> libtoolize: copying file 'build-aux/m4/libtool.m4'
> libtoolize: copying file 'build-aux/m4/ltoptions.m4'
> libtoolize: copying file 'build-aux/m4/ltsugar.m4'
> libtoolize: copying file 'build-aux/m4/ltversion.m4'
> libtoolize: copying file 'build-aux/m4/lt~obsolete.m4'
> configure.ac:10: installing 'build-aux/compile'
> configure.ac:9: installing 'build-aux/missing'
> Makefile.am: installing 'build-aux/depcomp'

-------------------------------------------------------------------
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating libsecp256k1.pc
config.status: creating src/libsecp256k1-config.h
config.status: src/libsecp256k1-config.h is unchanged
config.status: executing depfiles commands
config.status: executing libtool commands
[water@t ~./c-secp256k1]$ make
  CC       .c-secp256k1/src/tests-tests.o
/bin/sh: cannot open ./build-aux/depcomp: No such file or directory
*** Error code 2

Stop.
make: stopped in ./c-secp256k1

**Comment by ysangkok** [comment]
I have the same issue if I use FreeBSD make. You have to use `gmake`, then it works fine.

**Comment by gmaxwell** [comment]
If there is some gnuism that can be changed with a couple line fix, it would be good to do that-- otherwise, "use gmake on freebsd".
