### ISSUE TITLE
building a DLL with jni enabled fails

### ISSUE THREAD

**Issue by sken77** [bitcoin-core/secp256k1#563]
Hi, im trying to produce a DLL but it fails

` ./configure --host=x86_64-w64-mingw32 --enable-experimental --enable-module-ecdh --enable-jni`

![image](https://user-images.githubusercontent.com/22631338/46747467-0319d800-cc77-11e8-81b3-549175fca405.png)

**Comment by floreslorca** [comment]
this seems to be informative. just need to include that path.

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=760301

**Comment by floreslorca** [comment]
fix with adding `mingw* _JNI_INC_SUBDIRS="linux win32";;` in the m4 file

**Comment by ad19900913** [comment]
did u solve this problem?
seem i met the same problem, and i confuse about the error msg

**Comment by real-or-random** [comment]
Resolved by #682.
