### ISSUE TITLE
Integration in Zinc?

### ISSUE THREAD

**Issue by deuteragenie** [bitcoin-core/secp256k1#574]
Would it be desirable to integrate (part of?) this library in Zinc ?

See https://marc.info/?l=linux-netdev&m=153306437408074&w=2

**Comment by real-or-random** [comment]
I suppose this is rather a question that can be answered by the maintainers of Zinc.

**Comment by gmaxwell** [comment]
I don't think there is any particular demand for this curve in the kernel at least...

**Comment by deuteragenie** [comment]
I think wireguard, which is scheduled to be integrated in the Linux kernel, uses curve25519 for ECDH. 
Could it be replaced by secp256k1 and be faster and/or more secure and/or more maintainable ?
Though, as real-or-random mentioned above, this is rather a question for the maintainers of Zinc.

**Comment by gmaxwell** [comment]
I don't think secp256k1 is an especially attractive alternative if all you want is ECDH.   I have plenty of complaints about ed25519 in _other_ applications, but ECDH is the thing it was really made for and it does it quite well.
