### ISSUE TITLE
undefined reference to `secp256k1_ecdsa_sign_recoverable' and `secp256k1_ecdsa_recoverable_signature_serialize_compact'

### ISSUE THREAD

**Issue by reijin90** [bitcoin-core/secp256k1#576]
I can't make it work too: after running `make` where is the .so supposed to be located? it is not available in the `include` folder or root directory. 

I've added these includes:
```
#include "./libsecp256k1/include/secp256k1_recovery.h"
#include "./libsecp256k1/src/group.h"
#include "./libsecp256k1/src/scalar.h"
#include "./libsecp256k1/include/secp256k1.h"
```
And try to compile with:  `~/llvm7/bin/clang -g -O1 -fsanitize=fuzzer,address -o fuzz-libsecp256 fuzz-secp256.cc libsecp256k1/.libs/libsecp256k1.so.0.0.0` (this is essentially a clang call with additional instrumentation)

Which leads to these errors:
```
/fuzzing/fuzz-secp256.cc:61: undefined reference to `secp256k1_ecdsa_sign_recoverable'
/fuzzing/fuzz-secp256.cc:66: undefined reference to `secp256k1_ecdsa_recoverable_signature_serialize_compact'
```

I guess it is related to the location of my program?
```
-rw-rw-r--  1 master master     5410 Dez  7 16:59 fuzz-secp256.cc
drwxrwxr-x 10 master master     4096 Dez  7 17:12 libsecp256k1/
```

I don't quite understand why it is not working...

**Comment by real-or-random** [comment]
You're only supposed  to include the files in the include directory.

For the shared library: Have you tried make install?

**Comment by reijin90** [comment]
ok, i figured out how to make the .so file: `make all` created it in `.lib`.
I changed my imports to:
```
#include "./libsecp256k1/include/secp256k1_recovery.h"
#include "./libsecp256k1/include/secp256k1.h"
#include "./libsecp256k1/include/secp256k1_ecdh.h"
```

Still the same error though... It's a bit strange, as the calls to `secp256k1_context_create_sign_verify` and `secp256k1_ec_seckey_verify` don't seem to bother the compiler...

**Comment by reijin90** [comment]
Both missing functions are defined in `src/modules/recovery/main_impl.h` is that the issue? Do I need some special flags to enable that or sth.?

**Comment by real-or-random** [comment]
They're static and thus not exported. The reason is that the API is intentionally kept high-level to prevent wrong usage. Bad crypto APIs are a huge foot cannon.

If you want to fuzz the library, you may be better off extending the library (e. g., the tests) than linking against it. Don't except further help.

**Comment by reijin90** [comment]
> They're static and thus not exported. The reason is that the API is intentionally kept high-level to prevent wrong usage. Bad crypto APIs are a huge foot cannon.

I don't quite see where they are static, as the functions that are missing for the linker are inside the `include/secp256k1_recovery.h` and there is no `static` used in the `src/modules/recovery/main_impl.h`. But, yes I agree it's best to have the API high-level. In my case I'm just imitating the usage in the program that I'm testing. 
> If you want to fuzz the library, you may be better off extending the library (e. g., the tests) than linking against it.

Thanks for the tip. I'll look into it! :)
> Don't except further help.

Not quite sure what to make out of that. Did I offend you somehow? Or is it just "not supported" usage and therefore my problem?

**Comment by real-or-random** [comment]
> > They're static and thus not exported. The reason is that the API is intentionally kept high-level to prevent wrong usage. Bad crypto APIs are a huge foot cannon.
> 
> I don't quite see where they are static, as the functions that are missing for the linker are inside the `include/secp256k1_recovery.h` and there is no `static` used in the `src/modules/recovery/main_impl.h`. But, yes I agree it's best to have the API high-level. In my case I'm just imitating the usage in the program that I'm testing.

Oh yep sorry, I was wrong. But one is actually in `secp256k1.h`, that's why I was confused, and `secp256k1_context_create_sign_verify` does not exist (in this form). I think if you just want to use those, then just include `include/secp256k1.h`. The other headers are for specific modules.

> > Don't except further help.
> 
> Not quite sure what to make out of that. Did I offend you somehow? Or is it just "not supported" usage and therefore my problem?

No, don't worry. Now with these functions it is even supported usage, so everything is alright. Also I just wanted to express that I may not want to invest more time in this issue but for no particular reason other than that my time is limited.

**Comment by reijin90** [comment]
All right, thanks! :)

Thanks to your hint I managed to fix my problem by simply compiling the parts of the libray I need directly into the program. `clang -I libsecp256k1 -I libsecp256k1/src/` and some imports do the trick: `#include "./libsecp256k1/src/secp256k1.c"
#include "./libsecp256k1/src/modules/recovery/main_impl.h"`
