### ISSUE TITLE
Travis should build and test arm asm

### ISSUE THREAD

**Issue by gmaxwell** [bitcoin-core/secp256k1#598]

**Comment by gmaxwell** [comment]
Travis should also test make install.

**Comment by benma** [comment]
Related: Travis does not seem to run `./tests`. Is there a reason for that?

**Comment by real-or-random** [comment]
It does, see https://travis-ci.org/bitcoin-core/secp256k1/jobs/560256756#L708 for example.
It just runs the entire testsuite using `make check-TESTS`. Maybe we should just update the README.

**Comment by benma** [comment]
Of course!

Updated README here: https://github.com/bitcoin-core/secp256k1/pull/652

**Comment by real-or-random** [comment]
Travis should also test different window size settings.

**Comment by real-or-random** [comment]
Travis has now (alpha) support for ARM: 
https://blog.travis-ci.com/2019-10-07-multi-cpu-architecture-support

**Comment by elichai** [comment]
FWIW it's arm64, and we have asm only for arm, not arm64.

**Comment by laanwj** [comment]
It can build and run ARM executables on ARM64 (FWIW this is what we do in bitcoin )

**Comment by elichai** [comment]
Didn't know arm64 can execute arm binaries. i'll give this a try

**Comment by laanwj** [comment]
I think it's a feature that many SoCs have, including the one Travis happens to use, not a general requirement for arm64

**Comment by gmaxwell** [comment]
Even just having arm64 would be a big improvement. Sure, that wouldn't test that the arm ASM builds and works-- which is the critical thing motivating this issue, but there isn't anything blocking that as far as I know.

Similarly, there appears to be no BE host in this project's travis configuration. s390x is be, I believe. (lol)

**Comment by elichai** [comment]
CC https://github.com/bitcoin-core/secp256k1/pull/696

**Comment by real-or-random** [comment]
This has been solved by #930.
