### ISSUE TITLE
Is there a reference for the point doubling and point-addition algorithms that are used?

### ISSUE THREAD

**Issue by hadasz** [bitcoin-core/secp256k1#611]
I am writing an implementation of ECDSA for secp256k1 in a different language, and was wondering if there's a useful resource (paper, blog post, etc) describing the point-doubling and point-addition algorithms that are implemented [here](https://github.com/bitcoin-core/secp256k1/blob/master/sage/secp256k1.sage).

Thanks!

**Comment by gmaxwell** [comment]
The derivation of the variable time formulas is fairly straight-forward, given varrious algebraic properties of the curve (see comments in the code). The "unified" constant time formula is inspired by the paper cited here: https://github.com/bitcoin-core/secp256k1/blob/master/src/group_impl.h#L536  (though note, the formula merely unifies doubling and adding-- it is, not complete which is not obvious in the paper.).

**Comment by hadasz** [comment]
Got it, thanks
