### ISSUE TITLE
Fails to compile in node 12

### ISSUE THREAD

**Issue by satazor** [bitcoin-core/secp256k1#613]
Node 12 has just released but this library is failing to compile, maybe due to v8 changes.

You may see a travis log here: https://travis-ci.org/ipfs-shipyard/js-idm-wallet/jobs/524722975

**Comment by sipa** [comment]
This library has no javascript support, so I suspect you're reporting this in the wrong place.

**Comment by satazor** [comment]
Oops, I believe you are right. The right repo is: https://github.com/cryptocoinjs/secp256k1-node

Apologies.
