### ISSUE TITLE
Properly handle sscanf return value in ./src/secp256k1/src/tests.c

### ISSUE THREAD

**Issue by mustaphaabiola** [bitcoin-core/secp256k1#649]
A bug exists which allows the `sh` variable to be used uninitialized when sscanf returns EOF.

Observe:

https://github.com/bitcoin-core/secp256k1/blob/fa3301713549d118e57ebe6551d062903ddd6b63/src/tests.c#L5183-L5185

A simple fix would be to explicitly test if sscanf's return value is equal to 1.

**Comment by real-or-random** [comment]
Good catch. Can you open a pull request to fix this.

**Comment by mustaphaabiola** [comment]
> Good catch. Can you open a pull request to fix this?

Done.
