### ISSUE TITLE
Provide pkg-config modules for optional modules

### ISSUE THREAD

**Issue by ysangkok** [bitcoin-core/secp256k1#666]
pkg-config provides the option of having multiple modules per package. One can check for the existence of a module (`% pkg-config --exists libsecp256k1; echo $?`). If secp256k1 provided pkg-config modules for its optional modules like ECDH, one could check conveniently whether libsecp256k1 was built with ECDH, if one requires this.

I can make a patch for this if you think it is a good idea, please provide feedback.

Currently, libsecp256k1 provides just a single module:

```
$ pkg-config --print-provides libsecp256k1
libsecp256k1 = 0.1
```

**Comment by apoelstra** [comment]
What would be involved in this? Just a change to `configure.ac`?

**Comment by ysangkok** [comment]
@apoelstra See PR #675

**Comment by ysangkok** [comment]
Closing this since the linked PR has discussion which seems to suggest that this is not desired.
