### ISSUE TITLE
naming: privkey vs seckey

### ISSUE THREAD

**Issue by real-or-random** [bitcoin-core/secp256k1#670]
We have a bunch of `secp256k1_ec_privkey_` functions but then we have `secp256k1_ec_seckey_verify`. I think we should create a `privkey` alias for this function.

More generally, we sometimes write "private key" and sometimes "secret key", and all the `privkey` functions expect a `seckey` argument. This should be made consistent too.

**Comment by kroggen** [comment]
What about using the `privkey` as default and let the `seckey` as the alias? So the function names are consistent.

My vote goes to have the arguments named `privkey` too. Decreasing the amount of different names makes the code easier to understand.

**Comment by jonasnick** [comment]
The thing is called `seckey` everywhere except the `ec_privkey` function names. So let's keep that as a default.

**Comment by real-or-random** [comment]
Superseded by https://github.com/bitcoin-core/secp256k1/issues/671
