### ISSUE TITLE
No-float policy for secp256k1

### ISSUE THREAD

**Issue by laanwj** [bitcoin-core/secp256k1#683]
I think secp256k1 needs an explicit no-floating point policy, like the Linux kernel. This means no use of `float`, and no  `double` (and no `half`, no `long double` either).

- It has to be able to run in kernel context
- Boot and security processors tend to have no FP support (e.g. core 0 on the Sifive U54)
- FP hardware implementation is possibly inconsistent between platforms which is useless for cryptography

I mean for the main code; in the bench framework is fine, though with the assumption that it might be emulated and very slow.

(inspired by https://github.com/bitcoin-core/secp256k1/pull/658#issuecomment-548576364)

**Comment by elichai** [comment]
For the record it was a hypothetical. I wasn't serious in using floats... (which we obviously should almost never use ever)

**Comment by real-or-random** [comment]
No worries :)

**Comment by laanwj** [comment]
> For the record it was a hypothetical. I wasn't serious in using floats... (which we obviously should almost never use ever)

I know it was more or less a joke in your case!

But it's just good to have these things explicit, so developers as well as users of the library have some certainly.
