### ISSUE TITLE
Build on PHP7 fails: Cannot find config.m4

### ISSUE THREAD

**Issue by typoworx-de** [bitcoin-core/secp256k1#724]
Tried building module for PHP7.2 and PHP7.4 both complaining about missing config.m4:

```
$>phpize7.2 
Cannot find config.m4. 
Make sure that you run '/usr/bin/phpize7.2' in the top level source directory of the module
```

```
$>phpize7.4
Cannot find config.m4. 
Make sure that you run '/usr/bin/phpize7.4' in the top level source directory of the module
```

**Comment by real-or-random** [comment]
This is a C library built with autotools. We don't have PHP bindings in our repo here. Are you sure you've opened this issue in the right repo?

Related: https://github.com/bitcoin-core/secp256k1/issues/255

**Comment by typoworx-de** [comment]
@real-or-random yeah just noticed this as well re-viewing this. Seems to be related trying to https://github.com/Bit-Wasp/secp256k1-php in combination with this core library.
I think I got confused by the instructions there ...

**Comment by typoworx-de** [comment]
Thanks for the hint in right direction @real-or-random. The required PHP Extension wrapping this lib as PHP-Extension is inside this repository:
https://github.com/Bit-Wasp/secp256k1-php/tree/v0.2/secp256k1

Sorry for the confusion.
