### ISSUE TITLE
Make use of constant time ecdsa_sign code in ecdsa_sign_recoverable

### ISSUE THREAD

**Issue by jonasnick** [bitcoin-core/secp256k1#725]
We can not add `secp256k1_ecdsa_sign_recoverable` to `valgrind_ctime_tests` (added in PR #708) because it is mostly a copy of the old `ecdsa_sign` function which was not constant time in edge cases. Instead of fixing `sign_recoverable` and again having duplicate code we should add an internal function with the code shared between the two functions (similar to https://github.com/bitcoin-core/secp256k1/commit/ab4fd520cc9f995fb1d2ffe825a2747671b9848d).

Let's get https://github.com/bitcoin-core/secp256k1/pull/701 in first because it also touches `ecdsa_sign`.

**Comment by elichai** [comment]
@jonasnick hehe I didn't know this issue existed :)
