### ISSUE TITLE
Remove OpenSSL benchmarks?

### ISSUE THREAD

**Issue by real-or-random** [bitcoin-core/secp256k1#736]
I think OpenSSL is useful for cross-testing (see https://github.com/bitcoin-core/secp256k1/pull/635) but I find the benchmark are annoying:
 - They take very long.
 - It's currently not possible to disable them without disabling the OpenSSL tests.
 - Compilation of `benchmark_verify` is a special case in the build, see #735. 

I think the benchmarks were useful in the early days of this library to demonstrate that it outperforms OpenSSL but this not necessary anymore. 

Do people agree that we should remove them?

**Comment by elichai** [comment]
I'm fine with it.
But I think I'll look into implementing https://github.com/bitcoin-core/secp256k1/issues/716 this week to completely remote openssl

**Comment by sipa** [comment]
ACK (independent of whether we also get rid of the OpenSSL tests or not)

**Comment by real-or-random** [comment]
resolved by #983
