### ISSUE TITLE
[question] Reference to "Standards for Efficient Cryptography" (SEC2) 2.7.1.

### ISSUE THREAD

**Issue by kiminuo** [bitcoin-core/secp256k1#743]
Hi,

can anybody point me to the reference document? 

I have found https://www.secg.org/sec2-v2.pdf and and section "2.4.1  Recommended Parameters secp256k1" ... but it is 2.4.1 and not 2.7.1 as described in https://github.com/bitcoin-core/secp256k1/blob/59a8de8f64a21b37ea1a49e22dc83aa3aadfc9b0/src/field_5x52_impl.h#L35

Is 2.7.1 typo? Or have I found a wrong document?

Thanks!

**Comment by real-or-random** [comment]
It was 2.7.1 in version 1 of that document.
See https://www.secg.org/SEC2-Ver-1.0.pdf or https://www.secg.org/ for an overview.

**Comment by kiminuo** [comment]
Ah, I had a quick look at that document too. Must have overlooked that. Thanks!
