### ISSUE TITLE
JNI ERROR

### ISSUE THREAD

**Issue by rocqina** [bitcoin-core/secp256k1#764]
libsecp256k1 enabled: false
![image](https://user-images.githubusercontent.com/15166591/85375546-0cd99100-b569-11ea-8578-75c922060c46.png)

I build it like this
./autogen.sh
./configure --enable-jni --enable-experimental --enable-module-schnorr --enable-module-ecdh
make
then configure -Djava.library.path=/home/steve/secp256k1/.libs

but java can not load lib success
The System Info  macOs 10.14.6

**Comment by elichai** [comment]
Hi,
Please see https://github.com/bitcoin-core/secp256k1/pull/682 we no longer maintain JNI bindings in this repository, that PR has a few alternative that maintain bindings for JNI.
Good Luck!

**Comment by rocqina** [comment]
Thank you very much！
