### ISSUE TITLE
32bit armv7l valgrind error

### ISSUE THREAD

**Issue by rustyrussell** [bitcoin-core/secp256k1#847]
https://github.com/ElementsProject/lightning/issues/4203

Seems like gcc is turning the "*r = *a" into memcpy, and various (all?) callers have r == a.  Technically disallowed, but gcc may be allowed to make this assumption?

**Comment by real-or-random** [comment]
Ah, that's the same as https://github.com/bitcoin-core/secp256k1/issues/776, just not in a `-Os` build... Sad that it happens here too.

**Comment by elichai** [comment]
Now gcc too? :(

**Comment by real-or-random** [comment]
Oh indeed, so far we've seen this only with clang... Let's track this in #776.
