### ISSUE TITLE
Stable version of secp256k1. Where to get it?

### ISSUE THREAD

**Issue by alexandrkirilov** [bitcoin-core/secp256k1#853]
In libbitcoin-system/install.sh defined parameters for secp256k1 of master branch in current state:

`SECP256K1_OPTIONS=( "--disable-tests" "--enable-module-recovery" "--enable-endomorphism")`

If I am following them - I am getting this warning:

`configure: WARNING: unrecognized options: --enable-endomorphism`

Which version of secp256k1- stable or at least commit ID for it because there are no any released version found by me. Is there any way to get stable release?

Where to get older version that is OK for libbitcoin?
For now I have this troubles https://github.com/libbitcoin/libbitcoin-system/issues/1173 with secp256k1 when using it in application. How to fix it or at least where to start seeking solution?

**Comment by jonasnick** [comment]
There is no stable version of secp256k1 at this point. Either you remove the `--enable-endomorphism` option or you use the commit right before that option become the default (`63150ab4da1ef13ebfb4396064e1ff501dbd015e`).
