### ISSUE TITLE
Clang 5 emits -Wmissing-field-initializers warnings

### ISSUE THREAD

**Issue by hebasto** [bitcoin-core/secp256k1#855]
While compiling the Bitcoin Core master branch (https://github.com/bitcoin/bitcoin/commit/c1604483d34f745fe6dc77a5f1be4fcfad7408a7) with Clang 5 having the following warnings:
```
src/secp256k1.c:79:9: warning: missing field 'pre_g_128' initializer [-Wmissing-field-initializers]
    { 0 },
        ^
src/secp256k1.c:80:9: warning: missing field 'blind' initializer [-Wmissing-field-initializers]
    { 0 },
        ^
2 warnings generated.
```

**Comment by hebasto** [comment]
No warnings with Clang 6.

**Comment by hebasto** [comment]
Is https://reviews.llvm.org/D28148 a fix?

**Comment by real-or-random** [comment]
> Is https://reviews.llvm.org/D28148 a fix?

Probably.

The code is correct and I don't think it's an issue that we have a spurious warning with clang 5. Is there anything you expect us to do about this?

**Comment by hebasto** [comment]
> The code is correct and I don't think it's an issue that we have a spurious warning with clang 5. Is there anything you expect us to do about this?

I thought the issue could affect [my work](https://github.com/bitcoin/bitcoin/pull/20544) on the build system, as one of CI jobs builds with Clang 5, and `-Werror` is enabled by default now. But test passed.

Closing.

**Comment by real-or-random** [comment]
Ok, just ping us again if this turns out to be annoying in Core. 

This init list has created a bunch of warning in the past, in different variants and different compilers...
