### ISSUE TITLE
AV Alert on build - Win32:Malware-gen

### ISSUE THREAD

**Issue by unozerocode** [bitcoin-core/secp256k1#859]
Hi, not sure if this is real, but will post it here in case someone can check it out. 
When compiling an Elixir library on Windows that depends on secp256k1, an AV alert was issued on an emitted file conftest.exe
containing Win32:Malware-gen
I created the issue in that library but maybe it belongs here?

https://github.com/izelnakri/eth/issues/32

`==> mix_erlang_tasks
Compiling 4 files (.ex)
warning: String.to_char_list/1 is deprecated. Use String.to_charlist/1 instead
Found at 2 locations:
lib/util.ex:13: MixErlangTasks.Util.compile_files/2
lib/util.ex:14: MixErlangTasks.Util.compile_files/2

warning: String.to_char_list/1 is deprecated. Use String.to_charlist/1 instead
Found at 2 locations:
lib/mix/tasks/ct.ex:31: Mix.Tasks.Ct.run/1
lib/mix/tasks/ct.ex:32: Mix.Tasks.Ct.run/1

Generated mix_erlang_tasks app
c_src/build_deps.sh
Cloning into 'secp256k1'...
remote: Enumerating objects: 29, done.
remote: Counting objects: 100% (29/29), done.
remote: Compressing objects: 100% (23/23), done.
remote: Total 5919 (delta 9), reused 19 (delta 6), pack-reused 5890
Receiving objects: 100% (5919/5919), 2.48 MiB | 1.70 MiB/s, done.
Resolving deltas: 100% (4142/4142), done.
HEAD is now at d333521 Merge #494: Support OpenSSL versions >= 1.1 for ENABLE_OPENSSL_TESTS
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, build-aux'. libtoolize: copying file build-aux/ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIR, build-aux/m4'. libtoolize: copying file build-aux/m4/libtool.m4'
libtoolize: copying file build-aux/m4/ltoptions.m4' libtoolize: copying file build-aux/m4/ltsugar.m4'
libtoolize: copying file build-aux/m4/ltversion.m4' libtoolize: copying file build-aux/m4/lt~obsolete.m4'
configure.ac:26: installing build-aux/compile' configure.ac:5: installing build-aux/config.guess'
configure.ac:5: installing build-aux/config.sub' configure.ac:9: installing build-aux/install-sh'
configure.ac:9: installing build-aux/missing' Makefile.am: installing build-aux/depcomp'
checking build system type... i686-pc-mingw32
checking host system type... i686-pc-mingw32
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking how to print strings... printf
checking for style of include used by make... GNU
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.exe
checking for suffix of executables... .exe
checking whether we are cross compiling... configure: error: in /c/Users/Enrique/IdeaProjects/uzweb2/deps/libsecp256k1/c_src/secp256k1': configure: error: cannot run C compiled programs. If you meant to cross compile, use --host'.
See `config.log' for more details
make: *** [priv/libsecp256k1_nif.so] Error 1
Terminate batch job (Y/N)? y`

![image](https://user-images.githubusercontent.com/57536442/102921354-de723b00-4451-11eb-98dc-a9390e49e08d.png)

**Comment by real-or-random** [comment]
This looks like this bug: https://sourceforge.net/p/mingw/bugs/1990/

I'm pretty certain it's not related to our repo.

**Comment by unozerocode** [comment]
ok, will report it as a false positive, thanks.
