### ISSUE TITLE
build: configure script warnings on macOS

### ISSUE THREAD

**Issue by hebasto** [bitcoin-core/secp256k1#896]
Configuring the recent master branch (24d1656c328c932cd533f6f4bf80b345b6591f0d) on macOS Big Sur 11.2.1 (20D74), and receiving 4 messages `rm: conftest.dSYM: is a directory`:

```
% ./configure -q
rm: conftest.dSYM: is a directory
rm: conftest.dSYM: is a directory
rm: conftest.dSYM: is a directory
rm: conftest.dSYM: is a directory

Build Options:
  with ecmult precomp     = yes
  with external callbacks = no
  with benchmarks         = yes
  with tests              = yes
  with openssl tests      = yes
  with coverage           = no
  module ecdh             = no
  module recovery         = no
  module extrakeys        = no
  module schnorrsig       = no

  asm                     = x86_64
  bignum                  = no
  ecmult window size      = 15
  ecmult gen prec. bits   = 4

  valgrind                = no
  CC                      = gcc
  CFLAGS                  = -O2 -fvisibility=hidden -std=c89 -pedantic -Wall -Wextra -Wcast-align -Wnested-externs -Wshadow -Wstrict-prototypes -Wundef -Wno-unused-function -Wno-long-long -Wno-overlength-strings -W -g
  CPPFLAGS                = -I/usr/local/Cellar/valgrind/3.16.1/include 
  LDFLAGS                 = 

  CC_FOR_BUILD            = gcc
  CFLAGS_FOR_BUILD        = -O2 -fvisibility=hidden -std=c89 -pedantic -Wall -Wextra -Wcast-align -Wnested-externs -Wshadow -Wstrict-prototypes -Wundef -Wno-unused-function -Wno-long-long -Wno-overlength-strings -W -g
  CPPFLAGS_FOR_BUILD      = -I/usr/local/Cellar/valgrind/3.16.1/include 
  LDFLAGS_FOR_BUILD       =
```

Detailed:
```
% ./configure
...
checking whether gcc understands -c and -o together... rm: conftest.dSYM: is a directory
yes
...
checking the name lister (/usr/bin/nm -B) interface... rm: conftest.dSYM: is a directory
BSD nm
...
checking for archiver @FILE support... rm: conftest.dSYM: is a directory
no
...
checking command to parse /usr/bin/nm -B output from gcc object... rm: conftest.dSYM: is a directory
ok
...
```

**Comment by real-or-random** [comment]
So I guess you may have figured that out already but that's not a serious issue, it just means that some `conftest.dSYM` directory will be left in your tree. See https://lists.gnu.org/archive/html/bug-autoconf/2007-11/msg00017.html ...

What's the output of `glibtool --version` and `autoconf --version`?

**Comment by hebasto** [comment]
> Did you run `autogen.sh` again just to be sure?

Yess :)

> So I guess you may have figured that out already but that's not a serious issue, it just means that some `conftest.dSYM` directory will be left in your tree. See https://lists.gnu.org/archive/html/bug-autoconf/2007-11/msg00017.html ...

Yeah, I've read some mls, including that you point at, and I agree that's not a serious issue.

> What's the output of `glibtool --version` and `autoconf --version`? edit: and `autoreconf --version`?

```
% glibtool --version
glibtool (GNU libtool) 2.4.6
Written by Gordon Matzigkeit, 1996

Copyright (C) 2014 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
```
% autoconf --version
autoconf (GNU Autoconf) 2.69
Copyright (C) 2012 Free Software Foundation, Inc.
License GPLv3+/Autoconf: GNU GPL version 3 or later
<http://gnu.org/licenses/gpl.html>, <http://gnu.org/licenses/exceptions.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by David J. MacKenzie and Akim Demaille.
```
```
% autoreconf --version
autoreconf (GNU Autoconf) 2.69
Copyright (C) 2012 Free Software Foundation, Inc.
License GPLv3+/Autoconf: GNU GPL version 3 or later
<http://gnu.org/licenses/gpl.html>, <http://gnu.org/licenses/exceptions.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by David J. MacKenzie and Akim Demaille.
```

**Comment by real-or-random** [comment]
Hm, these are not the most recent versions but they should be recent enough then...
Cirrus CI shows the same issue: https://cirrus-ci.com/task/5325071847784448?command=test#L51

Can you try removing the directory and see if the error persists?

Looking at the the (old) Travis logs, I believe this was introduced by #862. Can you confirm this?
 
before: https://travis-ci.org/github/bitcoin-core/secp256k1/builds/754093307
after: https://travis-ci.org/github/bitcoin-core/secp256k1/builds/754127317
Make sure to look at "gcc" build (which is Apple's fake gcc).

**Comment by hebasto** [comment]
> Hm, these are not the most recent versions but they should be recent enough then...

Both packages are installed via Homebrew, btw:
- https://formulae.brew.sh/formula/autoconf
- https://formulae.brew.sh/formula/libtool

> Can you try removing the directory and see if the error persists?

`find . -type d` does not list such directories...

**Comment by hebasto** [comment]
> Looking at the the (old) Travis logs, I believe this was introduced by #862. Can you confirm this?

```
# just cloned repo
% git checkout 328aaef22a4378817dbc5b7f27cd6351858c0b6c
% ./autogen.sh
% ./configure -q
rm: conftest.dSYM: is a directory
rm: conftest.dSYM: is a directory
rm: conftest.dSYM: is a directory
...
rm: conftest.dSYM: is a directory
```

**Comment by hebasto** [comment]
I think #700 is the cause of warnings.
