### ISSUE TITLE
Cut a release of 0.X to support a homebrew formula for libsecp256k1

### ISSUE THREAD

**Issue by rickmark** [bitcoin-core/secp256k1#908]
Hello,

Today we have the ability to install `libbitcoin` and other core bitcoin libraries via homebrew but it builds and installs `libsecp256k1` as a private library.  I'm working both on moving `libsecp256k1` to it's own formula so it can be used independently of `libbitcoin` as well as `ruby-secp256k1` as native bindings for Ruby.  In order to support this we need to be able to refer to a cut release of `libsecp256k1`.  While I understand that it is not v1 yet, cutting a v0.8 or v0.9 for the non-experimental modules of core, ecdh, and recovery would enable wider adoption and contributions to this library.

The ask is to create a pre v1 release for homebrew.

**Comment by rickmark** [comment]
Proposed homebrew formula

[libsecp256k1.rb.txt](https://github.com/bitcoin-core/secp256k1/files/6192177/libsecp256k1.rb.txt)

**Comment by real-or-random** [comment]
Hey. Strictly speaking this is a duplicate of https://github.com/bitcoin-core/secp256k1/issues/286, and we continue discussion there.

I admit that referring you to a six years old issue is not really satisfactory. I think there's no compelling reason not to tag a pre-release. We just need to spend the time to do it. See also https://github.com/bitcoin-core/secp256k1/issues/856, any comments there will help.
