### ISSUE TITLE
Randomly message "core dumped" on secp256k1_fe_inv_var

### ISSUE THREAD

**Issue by CrunchyFanch** [bitcoin-core/secp256k1#910]
Hi, 
I try to implement a point addition in affine coordinate and to benchmark it.
Compilation are ok:
`gcc -o test2.exe -O2 -I secp256k1/src/ -I secp256k1/ test2.c -lgmp`

but i've sometimes  an error message on program execution (core dumped).
Not on every execution.

this is my code :

```c
#include "libsecp256k1-config.h"


#include <stdio.h>
#include <stdlib.h>

#include <time.h>

#include "include/secp256k1.h"
#include "assumptions.h"
#include "group.h"
#include "secp256k1.c"


#define ROUNDS 100000000`

static void light_add(secp256k1_fe *xr,secp256k1_fe *yr,  const secp256k1_fe *x1, const secp256k1_fe *y1, const secp256k1_fe *x2, const secp256k1_fe *y2){
        
        secp256k1_fe xtmp,ytmp,x1neg,x2neg,y2neg,xinv,m;
        xtmp = *x1;
        ytmp = *y1;
        int f;

        secp256k1_fe_negate(&x2neg,x2,f); //x2neg=-x2
        secp256k1_fe_negate(&y2neg,y2,f);//y2neg=-y2
        secp256k1_fe_negate(&x1neg,x1,f);//x1neg=-x1

        secp256k1_fe_add(&xtmp,&x2neg); //(x1-x2)
        secp256k1_fe_add(&ytmp,&y2neg);//(y1-y2)
     
        secp256k1_fe_inv_var(&xinv,&xtmp); //inverse_mod(x1-x2,P) 

        secp256k1_fe_mul(&m,&ytmp,&xinv); //m=(y1-y2)*(x1-x2)^-1
        secp256k1_fe_sqr(xr,&m);//m^2

        secp256k1_fe_add(xr,&x1neg); //xr=m^2-x1
        secp256k1_fe_add(xr,&x2neg); //xr=m^2-x1-x2

        xtmp = *xr;
        secp256k1_fe_add(&xtmp,&x1neg); //(xr-x1)
        secp256k1_fe_mul(&xtmp,&m,&xtmp); //m*(xr-x1)
        secp256k1_fe_add(&xtmp,y1); //y1+(xr-x1)
        secp256k1_fe_negate(yr,&xtmp,f); //yr=-(y1+(xr-x1))

}

int main(int argc, char** argv) {


    secp256k1_fe xr,yr;
    secp256k1_ge pt1,pt2;
    secp256k1_gej pt1j,pt2j;
    time_t now;


    secp256k1_gej_set_ge(&pt2j, &secp256k1_ge_const_g);

    secp256k1_gej_double_var(&pt2j, &pt2j, NULL);
    secp256k1_ge_set_gej(&pt2, &pt2j);               //pt2=2*G


    time(&now);
    printf("Today is : %s", ctime(&now));

    for (int i=0;i<ROUNDS;i++){

        light_add(&pt2.x,&pt2.y,&pt2.x,&pt2.y,&secp256k1_ge_const_g.x,&secp256k1_ge_const_g.y);
    }
    time(&now);
    printf("Today is : %s", ctime(&now));
}
```

The issue is difficult to track on debug mode because it's happens maybe 1 per 1 billion times additions but it seems to comes from 
secp256k1_fe_inv_var.

Do you know why there can have is this issue?
Regards
Crunchy

**Comment by sipa** [comment]
You're passing an uninitialized variable f as magnitude to fe_negate, that's unlikely to be correct.

**Comment by CrunchyFanch** [comment]
Thanks! 
It seems to works after 10 execs
I ve not fully understood what normalization is.
after which field operation do I have to normalize my fe type variables?

**Comment by real-or-random** [comment]
By the way, if you update to current master, secp256k1_fe_inv_var will be faster and won't need gmp / `-lgmp` anymore.

**Comment by CrunchyFanch** [comment]
thanks for advice. my version is the current master and it works without -lgmp

**Comment by sipa** [comment]
@CrunchyFanch Adding two fe's results in an fe whose magnitude is the sum of the input magnitudes. When negating you need to pass the input magnitude explicitly (or an upper bound of it), and the result will be one higher. Multiplication/inverting brings magnitude to 1. Explicit normalization does the same.

**Comment by sipa** [comment]
Compile with -DDEBUG and you'll get (very likely) errors if your magnitudes/normalization is wrong.

**Comment by CrunchyFanch** [comment]
@sipa ok so if a fe have a magnitude > 1 it's means than the number stored in the 5 limbs is > than P ?

**Comment by sipa** [comment]
@CrunchyFanch No, that's denormalization. Higher magnitude means that the individual limbs are larger some limit (see `secp256k1_fe_verify` in the individual implementation files).

**Comment by sipa** [comment]
For example for fe_5x52:

* magnitude m: limbs 0..3 in range 0..`(0xFFFFFFFFFFFFFULL*2m)`, limb 4 in range `0..(0x0FFFFFFFFFFFF*m)`.
* normalized: limbs 0..3 in range 0..0xFFFFFFFFFFFFF, limb 4 in range 0..0x0FFFFFFFFFFFF, and represented number is in range 0..p-1.

Normalized implies magnitude is 1, but also means there is just a single representation for any given field number.

**Comment by CrunchyFanch** [comment]
@sipa ok that's clear .

**Comment by CrunchyFanch** [comment]
uses of 52bits for limbs instead of 64 bits is a way to speed up the addition operation between limbs?

**Comment by CrunchyFanch** [comment]
@real-or-random the cost of the point addition is the purpose of my project. Do you think than gej addition without mod inv will be faster or slower than ge addition with mod_inv?

**Comment by sipa** [comment]
@CrunchyFanch Yes, a lot. The entire reason why jacobian coordinates are used is to avoid inverses.

Since #831 inverses are a lot faster, but even with that, I believe ge_add_gej will still be 5x-10x faster than a point addition that needs an inverse.

**Comment by CrunchyFanch** [comment]
@sipa thanks. that's what i'll think too but my benchmark doesn't find this difference of 5x as expected.

**Comment by sipa** [comment]
@CrunchyFanch Can you paste your full code somewhere?

**Comment by CrunchyFanch** [comment]
`int main(int argc, char** argv) {

    
    secp256k1_fe x1,x2,y1,y2,fe_inv;
    secp256k1_fe xr,yr;
    secp256k1_gej pt1,pt2,pt3;
    unsigned char x_bin[32];
    time_t now;

    secp256k1_gej_set_ge(&pt1, &secp256k1_ge_const_g);


    time(&now);
    printf("Today is : %s", ctime(&now));
    for (int i=0;i<ROUNDS;i++){
        secp256k1_gej_add_ge_var(&pt1,&pt1,&secp256k1_ge_const_g,&xr);
        // secp256k1_gej_add_ge_var(&diff, &diff, &secp256k1_ge_const_g,  NULL);
        
    }
    time(&now);
    printf("Today is : %s", ctime(&now));`

is slower in execution time than the main() above

**Comment by sipa** [comment]
Your code above is invalid (it still doesn't set f). Can you update it?

**Comment by CrunchyFanch** [comment]
you're welcome !

**Comment by CrunchyFanch** [comment]
'#include "libsecp256k1-config.h"


#include <stdio.h>
#include <stdlib.h>

#include <time.h>

#include "include/secp256k1.h"
#include "assumptions.h"
#include "group.h"
#include "secp256k1.c"
#include "testrand_impl.h"

#define ROUNDS 10000000

int main(int argc, char** argv) {

    
    secp256k1_fe x1,x2,y1,y2,fe_inv;
    secp256k1_fe xr,yr;
    secp256k1_gej pt1,pt2,pt3;



    unsigned char x_bin[32];
    time_t now;

    // secp256k1_gej_set_ge(&pt, &secp256k1_ge_const_g);
    secp256k1_gej_set_ge(&pt1, &secp256k1_ge_const_g);
    // secp256k1_gej_set_ge(&pt2, &secp256k1_ge_const_g);
    


    time(&now);
    printf("Today is : %s", ctime(&now));
    for (int i=0;i<ROUNDS;i++){
        secp256k1_gej_add_ge_var(&pt1,&pt1,&secp256k1_ge_const_g,&xr);

    }
    time(&now);
    printf("Today is : %s", ctime(&now));
}'

took 16sec on my computer

**Comment by CrunchyFanch** [comment]
and 
`#include "libsecp256k1-config.h"


#include <stdio.h>
#include <stdlib.h>

#include <time.h>

#include "include/secp256k1.h"
#include "assumptions.h"
#include "group.h"
#include "secp256k1.c"


#define ROUNDS 10000000


static void light_add(secp256k1_fe *xr,secp256k1_fe *yr,  const secp256k1_fe *x1, const secp256k1_fe *y1, const secp256k1_fe *x2, const secp256k1_fe *y2){
        
        secp256k1_fe xtmp,ytmp,x1neg,x2neg,y2neg,xinv,m;
        xtmp = *x1;
        ytmp = *y1;
        int f=1;

        secp256k1_fe_negate(&x2neg,x2,f); //x2neg=-x2
        secp256k1_fe_negate(&y2neg,y2,f);//y2neg=-y2
        secp256k1_fe_negate(&x1neg,x1,f);//x1neg=-x1

        secp256k1_fe_add(&xtmp,&x2neg); //(x1-x2)
        secp256k1_fe_add(&ytmp,&y2neg);//(y1-y2)
     
        secp256k1_fe_inv_var(&xinv,&xtmp); //inverse_mod(x1-x2,P)
        secp256k1_fe_mul(&m,&ytmp,&xinv); //m=(y1-y2)*(x1-x2)^1
        secp256k1_fe_sqr(xr,&m);//m^2

        secp256k1_fe_add(xr,&x1neg); //xr=m^2-x1
        secp256k1_fe_add(xr,&x2neg); //xr=m^2-x1-x2

        xtmp = *xr;
        secp256k1_fe_add(&xtmp,&x1neg); //(xr-x1)
        secp256k1_fe_mul(&xtmp,&m,&xtmp); //m*(xr-x1)
        secp256k1_fe_add(&xtmp,y1); //y1+(xr-x1)
        secp256k1_fe_negate(yr,&xtmp,f); //yr=-(y1+(xr-x1))

}



int main(int argc, char** argv) {


    secp256k1_fe xr,yr;
    secp256k1_ge pt1,pt2;
    secp256k1_gej pt1j,pt2j;
    time_t now;


    secp256k1_gej_set_ge(&pt2j, &secp256k1_ge_const_g);

    secp256k1_gej_double_var(&pt2j, &pt2j, NULL);
    secp256k1_ge_set_gej(&pt2, &pt2j);               //pt2=2*G


    time(&now);
    printf("Today is : %s", ctime(&now));

    for (int i=0;i<ROUNDS;i++){

        light_add(&pt2.x,&pt2.y,&pt2.x,&pt2.y,&secp256k1_ge_const_g.x,&secp256k1_ge_const_g.y);
    }
    time(&now);
    printf("Today is : %s", ctime(&now));
}`
took 17sec

**Comment by sipa** [comment]
2.7s vs. 11.7s here.

**Comment by sipa** [comment]
I also get assertion errors with your code when compiled with `-DVERIFY` here. Are you sure it's actually computing the right thing?

**Comment by sipa** [comment]
I suggest adding your code as a benchmark to bench_internal.c, and then running it in the normal compilation environment. If you compile by hand compilation flags or configuration could be off/suboptimal.

**Comment by CrunchyFanch** [comment]
`crunchy@crunchy-ESPRIMO-C710:~/PG/c/$ gcc -o test2.exe -O2 -I secp256k1/src/ -I secp256k1/ test2.c 
crunchy@crunchy-ESPRIMO-C710:~/PG/c/$ ./test2.exe 
Today is : Wed Mar 24 21:30:17 2021
Today is : Wed Mar 24 21:30:33 2021
crunchy@crunchy-ESPRIMO-C710:~/PG/c/$ gcc -o test3.exe -O2 -I secp256k1/src/ -I secp256k1/ test3.c 
crunchy@crunchy-ESPRIMO-C710:~/PG/c/$ ./test3.exe 
Today is : Wed Mar 24 21:31:34 2021
Today is : Wed Mar 24 21:31:49 2021
`

**Comment by CrunchyFanch** [comment]
test2.c is the first and test3.c is the second
sorry but i ve problem with formatting

**Comment by CrunchyFanch** [comment]
ok l'll do your suggestion of compilation

**Comment by CrunchyFanch** [comment]
Do you want that i close this issue?

**Comment by sipa** [comment]
I think the issue is solved :)
