### ISSUE TITLE
How to build  bitcoin-core/secp256k1  on windows

### ISSUE THREAD

**Issue by Stonica** [bitcoin-core/secp256k1#917]
I am to use  `bitcoin-core/secp256k1` on windows but has found any documentation, can someone help?

**Comment by real-or-random** [comment]
This is a C library that should compile fine on Windows.

If you're looking for generic instructions on how to setup a build environment on Windows, see https://github.com/bitcoin/bitcoin/blob/master/doc/build-windows.md . These are docs for a Bitcoin Core build, which includes a libsecp256k1 build, though some of things mentioned there may not be necessary if you're only interested in libsecp256k1. 

If you're using Microsoft Visual C, then this may be helpful: https://github.com/bitcoin/bitcoin/blob/master/build_msvc/libsecp256k1/libsecp256k1.vcxproj
