### ISSUE TITLE
Make it impossible to build without SECP256K1_BUILD defined

### ISSUE THREAD

**Issue by gmaxwell** [bitcoin-core/secp256k1#927]
If the library itself is compiled without -DSECP256K1_BUILD then it will be (minorly) miscompiled:  all the nullness checks on the interfaces which specify that their arguments be non-null will get optimized out (the exported symbols also won't get flagged for windows, but presumably where that matters it'll get noticed).

Is there any reason to not just have secp256k1.c #define SECP256K1_BUILD before including any headers and then drop any requirement for the build system?

If that can't be done, it should probably check and #error if it isn't defined.  But making it configuration-free seems much better to me.

**Comment by real-or-random** [comment]
> Is there any reason to not just have secp256k1.c #define SECP256K1_BUILD before including any headers and then drop any requirement for the build system?

I always wondered why it's not set in the `.c` file. I don't think there's a reason. We should do it (and see if it breaks anything). As you point out, this is a pitfall currently.

**Comment by elichai** [comment]
Related, for a while rust-secp256k1 didn't define this: https://github.com/rust-bitcoin/rust-secp256k1/pull/35

**Comment by sipa** [comment]
I don't think there is a reason not to set it in secp256k1.c directly.
