### ISSUE TITLE
Code Crashes on the call of ecmult_gen_context_build

### ISSUE THREAD

**Issue by aleksandrosbalkonis** [bitcoin-core/secp256k1#972]
The code works great on my computer but when I try to upload it on the esp32 from Arduino IDE on execution it crashes exactly on the call of the secp256k1_ecmult_gen_context_build() function. I am having a really hard time pinpointing the problem. Can anyone help?

**Comment by sipa** [comment]
Is it possible it is running out of memory?

**Comment by aleksandrosbalkonis** [comment]
It is but I do not understand why it crashes on the call of the function and not inside on some of the allocations or the pointer operations. And I dont get any error callbacks like I do when I set  the ECMULT_GEN_PREC_BITS to 8.

**Comment by real-or-random** [comment]
What kind of crash is it? 

> It is but I do not understand why it crashes on the call of the function and not inside on some of the allocations or the pointer operations.

How do you tell the exact location? That's usually hard to do because the compiler may reorder code etc.

Do you use the "preallocated" API?

**Comment by aleksandrosbalkonis** [comment]
It is without USE_ECMULT_STATIC_PRECOMPUTATION. It resets the esp32 and starts from the beginning. I used the usual printf strategy and since I know that the compiler might rearrange the code or delay a print, I added a big for loop at the beginning of the ecp256k1_ecmult_gen_context_build() function and added the rest of the code in an if statement that waits for the for loop to end. There was a printf in the forloop but it was never printed. 
funct(){
    for 10000{
        print()
        if 10000 {flag = 1}
    }
   if flag = 1{
       funct code
    }
}

**Comment by apoelstra** [comment]
If you are running out of memory it's also possible that the crash will be delayed until you actually try to access the memory, if the kernel is doing precommit.

**Comment by sipa** [comment]
Using static precomputation may help. I'm not familiar with that hardware, but I suspect you have more space for binaries mapped from disk than usable RAM at runtime.

**Comment by real-or-random** [comment]
> Using static precomputation may help. I'm not familiar with that hardware, but I suspect you have more space for binaries mapped from disk than usable RAM at runtime.

Indeed, this will probably solve your issue.

I'm currently working on a PR (not yet opened) that will -- if it gets merged -- make static precomputation mandatory in the future.  So switching to static precomputation may be a good idea anyway.

Until that PR is here, you need to create the `src/ecmult_static_context.h` file. Just run `./configure --enable-ecmult-static-precomputation --with-ecmult-gen-precision=X` where `X` is the value of `ECMULT_GEN_PREC_BITS` you want to use, and then run `make` as normal. This will build the library for your computer, which includes creating the `src/ecmult_static_context.h` file. Then you can use the generated file on Arduino, too.

**Comment by aleksandrosbalkonis** [comment]
For anyone trying to do what I do. Try also setting Defining the --with-ecmult-window=x  2 <=x <=24 in my case I had to set it to a small value to save memory (2 OR  4).

**Comment by real-or-random** [comment]
> For anyone trying to do what I do. Try also setting adding the --with-ecmult-window=x 2 <=x <=24 in my case I had to set it to a small value to save memory (2 OR 4).

This shouldn't be necessary on the current master. Are you on an older commit?

**Comment by aleksandrosbalkonis** [comment]
The default value is set to be at 15 witch generates 1.8MB (1.6MB after compression ) of code. When I tried flashing the program to the esp, the esp kept restarting without parsing the code at all. Probably a memory fault. By setting it to 2 it generated 0.8MB(0.55MB after compression) of code and it works great. No I am using the latest version.

**Comment by real-or-random** [comment]
> The default value is set to be at 15 witch generates 1.8MB (1.6MB after compression ) of code. When I tried flashing the program to the esp, the esp kept restarting without parsing the code at all. Probably a memory fault. By setting it to 2 it generated 0.8MB(0.55MB after compression) of code and it works great. No I am using the latest version.

Ok yes, this makes sense.
